### ISSUE TITLE
Return range along with line and column

### ISSUE THREAD

**Issue by UziTech** [squizlabs/PHP_CodeSniffer#1000]
Right now PHPCS returns just the line and column of the beginning of an offending token.

It would be nice for linters to be able to underline an entire token or multiple tokens that are breaking a rule instead of just the first character.

**Comment by gsherwood** [comment]
I had a look into this again and the only thing I can do is add a `length` value along with `column` and `line` to the CSV, XML, and JSON reports.

This really isn't that useful because it's not really the exact scope of the error. It's just the length of the token that the error was generated on.

There is no way to report an error that covers multiple tokens, and I can't see that ever being added.

For single token errors (as they all are now) a linter can figure out the token content by matching to the next whitespace character. I don't really need to change the reports for this.

On a related note, the new code report in version 3 provides similar functionality and only underlines a single token. I still think that is useful. Docs are here (can't see the underline in the docs though): https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting#printing-a-code-report

I'm going to close this as I no longer have any intention of making this change.
