### ISSUE TITLE
Function opening brace placement when using PSR-2

### ISSUE THREAD

**Issue by ravage84** [squizlabs/PHP_CodeSniffer#1037]
CakePHP 3.x adheres to PSR-2. Thus a valid function opening brace could look like:

``` php
 public function fooBar(
        $param1 = null,
        $param2 = null,
        $param3 = null,
    ) {
```

It seems brace placements like this get counted as "same line", as I have found out with the following file:

https://github.com/cakephp/cakephp/blob/3.2.10/src/View/AjaxView.php#L48

Which is one of the 0.13 % cases mentioned int he Analysis of Coding Conventions for CakePHP:
http://squizlabs.github.io/PHP_CodeSniffer/analysis/cakephp/cakephp/index.html#function-opening-brace-placement

**Comment by gsherwood** [comment]
I thought about this one for a while when I first did those reports. This formatting is a special case where you actually do leave the brace on the same line as the closing parenthesis when it is normally not done. I use the exact same formatting for multi-line declarations, so the PHPCS project reports have the same issue, which is why I was trying to figure out what to do.

I actually considered adding a 3rd type of value for this specific case because I wanted to differentiate between code like this:
```php
public function fooBar(
    $param1 = null,
    $param2 = null,
    $param3 = null
) {
```
and code like this:
```php
public function fooBar
    (
    $param1 = null,
    $param2 = null,
    $param3 = null
    )
{
```
I'm not 100% sure what I'll do just yet.

**Comment by ravage84** [comment]
A third type sounds good. Probably the cleanest solution. :+1:

**Comment by gsherwood** [comment]
Closing as this obviously isn't going to get done
