### ISSUE TITLE
configuration option for cache

### ISSUE THREAD

**Issue by mathroc** [squizlabs/PHP_CodeSniffer#1080]
I couldn't find configuration options in [the documentation](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options) to enable cache and set the cache file location. I tried with `cache` = `true` & `cacheFile` = `/path/to/cache.json` but that's not it ^^

Is it already possible (and just not documented yet)? if not, could this be added ? (I can take a shot at making a PR for it)

**Comment by aik099** [comment]
This is 3.0 version feature only. Are you using PHPCS 3.0+?

**Comment by aik099** [comment]
The release page of 3.0.0a1 version (see https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0a1) explains (maybe not in documentation yet) how to set cache:


> * Added optional caching of results between runs (request #530)
>  * Enable the cache by using the --cache command line argument
>  * If you want the cache file written somewhere specific, use --cache=/path/to/cacheFile
>  * Use the command "phpcs --config-set cache true" to turn caching on by default
>  * Use the --no-cache command line argument to disable caching if it is being turned on automatically

**Comment by mathroc** [comment]
yes I'm using 3.0.0a1, the cache is working nicely with the command line arguments, I'd just like to set that in the config instead of having to repeat the parameters all the time

**Comment by aik099** [comment]
> `phpcs --config-set cache true`

This should do it.

Probably following would allow to set cache path as well:

`phpcs --config-set cache /path/to/cacheFile`

**Comment by mathroc** [comment]
that's what I hoped for but it does not

**Comment by gsherwood** [comment]
Yeah, I didn't add a config value for that. The reason is that you'd probably want different cache file locations for each project you have, so I envisaged having a phpcs.xml file in the project root that specified the cache file path (and other defaults) for the project itself.

But I don't see any reason not to have a config var for it (and probably few other things I don't have vars for yet) so I think it's a good idea.

**Comment by gsherwood** [comment]
I started doing this and it became more obvious why I haven't done it - setting file paths inside config vars is tough. Because these file paths can be relative, and can be invalid depending on where you are actually running PHPCS from, it makes their usage problematic.

So what I would have to do here is ensure that the file path is absolute if you are setting it via a config var, but it will still be validated each time PHPCS is run to ensure the path is still valid.

If the path does become invalid, you'd need to change the config var before PHPCS could actually run again. That's not typically what config vars should be doing - once you set them they should remain valid.

So I'm in two minds about adding this in, or adding config vars for any other files paths.

**Comment by mathroc** [comment]
> Yeah, I didn't add a config value for that. The reason is that you'd probably want different cache file locations for each project you have, so I envisaged having a phpcs.xml file in the project root that specified the cache file path (and other defaults) for the project itself.

yeah, it makes sense to have different cache file for each project. I'm using it in a docker container with docker-compose so I'm actually having a different config file per project

> I started doing this and it became more obvious why I haven't done it - setting file paths inside config vars is tough

Indeed, it might lead to unexpected behavior if a relative path is set and you run phpcs from different location. 
I didn't know I could set it i the ruleset so that will be enough for me as I've already have one in my projects

Maybe another idea for the config would be to read config from ./.phpcs.php (from working dir and parent dirs) and merging those values with /usr/local/lib/php/data/PHP_CodeSniffer/CodeSniffer.conf

**Comment by gsherwood** [comment]
> Maybe another idea for the config would be to read config from ./.phpcs.php (from working dir and parent dirs) and merging those values with /usr/local/lib/php/data/PHP_CodeSniffer/CodeSniffer.conf

That's what the phpcs.xml files are for, but the "merging" isn't great in the 2.x version. I completely rewrote all that code in the 3.x version (current released as 3.0.0a1) and I think it works much better now. It favours the options you put on the command line, but it also sources from the user's conf and the phpcs.xml file it finds.

**Comment by mathroc** [comment]
ok, thank you all for your answers
