### ISSUE TITLE
PHP_CodeSniffer_CLI::getDefaults does not set default value for 'quiet'

### ISSUE THREAD

**Issue by ryanneufeld** [squizlabs/PHP_CodeSniffer#1081]
When using PHPCS from within unit tests (setting PHP_CODESNIFFER_IN_TESTS == true)

This leads to an "undefined index: quiet" when setting something like `self::$phpcs->cli->setCommandLineValues(array('-p', '--colors'));` in a unit test.

**Comment by gsherwood** [comment]
PHPCS only sets a minimum of values during testing; just for things it thinks it might need.

What is your use case for needing progress and colour output during a unit test? Setting the quiet option may not be enough for what you are doing, which is why I'm asking.

**Comment by ryanneufeld** [comment]
I'm troubleshooting the wing/php-compatibility sniffs. His unit tests set
those values.

**Comment by gsherwood** [comment]
I was just looking through the code and I noticed that PHPCS already sets the quiet option during testing in master. I remember doing this for for the PHPUnit `-p` option. It was reported and fixed in #1066 about a week ago, so I think that's the fix you'd be after.

I'll close this as a duplicate because your use case doesn't need anything else besides this fix.

**Comment by ryanneufeld** [comment]
Thanks for this, though it looks like you've not tagged 2.6.3 for release yet. Do you have an ETA for that?

**Comment by gsherwood** [comment]
> Do you have an ETA for that?

I don't. 2.6.2 only just came out, so it's going to be several weeks at the earliest. I have a long list of things to put into the next version, which will be 2.7.0.
