### ISSUE TITLE
phpcbf leaves extra spaces when fixing Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis

### ISSUE THREAD

**Issue by nkovacs** [squizlabs/PHP_CodeSniffer#1139]
Fixing this file using the PSR2 standard:

```
<?php

if ($test)    { /*one space after the bracket*/
    echo 'true';
}
```

will result in:

```
<?php

if ($test) {     /*one space after the bracket*/
    echo 'true';
}
```

It should become

```
<?php

if ($test) { /*one space after the bracket*/
    echo 'true';
}
```

**Comment by gsherwood** [comment]
This is a result of this sniff having to support code that looks like this:
```php
if ($test) /*one space after the bracket*/ {
    echo 'true';
}
```
and this:
```php
if ($test) 
    /*one space after the bracket*/
{
    echo 'true';
}
```
So the fix just moves the brace rather than changing the tokens between the closing parenthesis and the brace. I'll just need to do a little extra work in the fix to detect if the tokens are just whitespace and replace them if so.

**Comment by gsherwood** [comment]
The result of this change is going to be a slight change to the behaviour of a specific fix. For this code:
```php
if ($i == 0)
{ // this is ok
    $i = 1;
}
```
It used to be fixed like this:
```php
if ($i == 0) {
 // this is ok
    $i = 1;
}
```
But will now be fixed like this:
```php
if ($i == 0) { // this is ok
    $i = 1;
}
```
Which I think is fine.

**Comment by nkovacs** [comment]
Thanks!
