### ISSUE TITLE
Suggestion naming convention Allowed List for naming convention transition

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1145]
For a project that is transitioning from one type of naming convention to another; it would be nice to be able to specify an Allowed List file of variable or function names that the new standard would not be enforced against. 

For example transitioning from snake_case_naming to camelCaseNaming. Due to B/C considerations, the old names have to remain for a period of time but new code in the project should have the new naming convention enforced.

**Comment by gsherwood** [comment]
It definitely doesn't make sense as a core feature because the core doesn't actually check naming, so it would have to be sniff-based. That would make the configuration based on a sniff param and not a file path, but it seems easily achievable in any sniffs that check naming conventions. The config param would need to be added to all of them though.

**Comment by aik099** [comment]
Please keep performance in mind, because adding an IF statement to every code piece, that checks variable naming would slow things down.

**Comment by gsherwood** [comment]
Closing as I've had no additional interest or PRs for this.
