### ISSUE TITLE
Question: anyway of controlling the brace style sniff used by `PEAR.Functions.FunctionDeclaration`?

### ISSUE THREAD

**Issue by u01jmg3** [squizlabs/PHP_CodeSniffer#1154]
Whilst using the `PEAR.Functions.FunctionDeclaration` I noticed it [enforces a bracing style](https://github.com/squizlabs/PHP_CodeSniffer/blob/e11f25393c3e5795ff87f2ccb2c156c63d6a13b3/CodeSniffer/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php#L233-L245). Is there anyway to control this?

Although the following doesn't work, it demonstrates what I am looking to do.

```xml
<rule ref="PEAR.Functions.FunctionDeclaration">
    <exclude name="Generic.Functions.OpeningFunctionBraceKernighanRitchie.BraceOnNewLine" />
    <exclude name="Generic.Functions.OpeningFunctionBraceBsdAllman.BraceOnSameLine" />
</rule>
```

**Comment by aik099** [comment]
You can include these back in your custom standard based on PEAR.

**Comment by u01jmg3** [comment]
Thank you - could you provide an example?

**Comment by gsherwood** [comment]
If you run PHPCS with the `-s` command line argument, it shows you the error codes for the messages it produces. As the PEAR sniff is generating these errors, the codes will show as `PEAR.Functions.FunctionDeclaration.something`. For example:
```
Opening brace should be on a new line (PEAR.Functions.FunctionDeclaration.BraceOnSameLine)
```
This is so that you don't accidentally exclude messages from other sniffs while trying to change this one. If you excluded those generic sniff codes, you'd never be able to use another sniff that makes use of them, or manually include them yourself.

So in this case, if you want to exclude those messages from this sniff, exclude `PEAR.Functions.FunctionDeclaration.BraceOnSameLine` and `PEAR.Functions.FunctionDeclaration.BraceOnNewLine` instead of the Generic sniff messages.

**Comment by u01jmg3** [comment]
Thanks @gsherwood, the following did the trick. Will keep the `-s` option in mind for next time.

```xml
<rule ref="PEAR.Functions.FunctionDeclaration">
    <exclude name="PEAR.Functions.FunctionDeclaration.BraceOnNewLine" />
    <exclude name="PEAR.Functions.FunctionDeclaration.BraceOnSameLine" />
</rule>
```

**Comment by gsherwood** [comment]
Good new.
