### ISSUE TITLE
Writing to file specifying in config?

### ISSUE THREAD

**Issue by dingo-d** [squizlabs/PHP_CodeSniffer#1171]
I can set the report type in the config settings of sniffer, but if I want to write report in a .txt file I need to specify 

```
$ phpcs --report=txt --report-file=/path/to/report.txt /path/to/code
```

I read through the wiki but didn't find a mention if it's possible to use `php config-set` with report file name, type and path.

Would be cool if that would be an option.

**Comment by aik099** [comment]
The `phpcs config-set` sets setting globally and not per-project. What is the use case, when you always want report to be stored into text file instead of shown on screen?

**Comment by dingo-d** [comment]
I'm sniffing through a WordPress theme, and there are lots of php files to go through (130 or so), so it's easier to have all the errors in a txt file I can go through, and not having to sniff though it all every time. 

But I see your point, since config is global, for a different project I'd still have the report in that file, and I could accidentally overwrite it. Didn't think it through I guess :D

**Comment by gsherwood** [comment]
An alternative is to use a custom ruleset.xml file (or add a phpcs.xml to your project's root dir) where you specify the specific command line arguments you want hard-coded for that project. You can also use it to customise your coding standard.

Some docs here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

You would want to include the following in a custom ruleset:
```xml
 <arg name="report-file" value="/path/to/report.txt"/>
```
(Note that I didn't include report=txt because there is no such report in PHPCS. I don't know which one you actually want - maybe `full` or `summary`)

**Comment by dingo-d** [comment]
I usually output full, but I think aik099 had good arguments. Writing always to the same file could cause some issues down the road.
