### ISSUE TITLE
Sniff discovery in a standard broken in 2.7.1

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#1205]
When I try to run unit tests on my standard using PHP_CodeSniffer 2.7.1 (current `master` branch) it will fail: https://travis-ci.org/aik099/CodingStandard/jobs/172735887

```
...
1) CodingStandard_Tests_Array_ArrayUnitTest::testStandard
PHP_CodeSniffer_Exception: Referenced sniff "CodingStandard.Array.Array" does not exist
/home/travis/build/aik099/CodingStandard/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1167
/home/travis/build/aik099/CodingStandard/vendor/squizlabs/php_codesniffer/CodeSniffer.php:550
/home/travis/build/aik099/CodingStandard/TestSuite/AbstractSniffUnitTest.php:74

2) CodingStandard_Tests_Classes_ClassCreateInstanceUnitTest::testStandard
PHP_CodeSniffer_Exception: Referenced sniff "CodingStandard.Classes.ClassCreateInstance" does not exist
...
```

No issues happen with PHP_CodeSniffer 2.7.0 version.

**Comment by gsherwood** [comment]
There have been changes to the core test runner so that ruleset.xml file are not processed when a test is running. Previously, the entire standard would load up and PHPCS would then say a single sniff was to be used, but all the extra rules (including exclude rules) would also run and cause files to be missed or improperly tested.

Perhaps this change has affected your custom test runner.

You'll probably need to follow the path through the code and see what is different between 2.7.0 and master for your tests. Unfortunately, I don't have the time to do this myself at the moment, so hopefully you do.

**Comment by aik099** [comment]
Thanks, I'll look into that. Hopefully I can adapt my test runner to work in all PHPCS versions. I'll post a link to commit with a fix so that anybody having similar issue can do the same.

**Comment by gsherwood** [comment]
Closing, but please post again if there are specific issues that need fixing.

**Comment by nkovacs** [comment]
I have this problem too.

`initStandard` calls `_expandRulesetReference` with the name of the sniff (Application.Arrays.ArrayDeclaration) and the directory containing the ruleset.xml (https://github.com/hellowearemito/yii2-coding-standards/tree/master/Application).

`_expandRulesetReference` can't find the sniff. It doesn't use `$rulesetDir`, since `$ref` doesn't start with a dot. It instead tries to find the standard in the installed standard path, so it can't find it.

**Comment by nkovacs** [comment]
I fixed it by setting `installed_paths` to the location of my standards: https://github.com/hellowearemito/yii2-coding-standards/commit/4525486abc636b0582e54e0b97f413926f3d6e51#diff-11bf1ef76079c183ca80095368e707eaR80

**Comment by aik099** [comment]
Thank you @nkovacs , you saved my day. I guess built-in PHP_CodeSniffer test runner should be updated to do this as well.
