### ISSUE TITLE
snake_case to camelCase

### ISSUE THREAD

**Issue by harikt** [squizlabs/PHP_CodeSniffer#1207]
Hi,

I was trying to figure out, if there is a way to convert in phpcbf to convert the snake_case methods to camelCase. I did tried different search, but looks I didn't find what I was looking for.

It would be nice, if there is some documentation how to build an extension when using the phpcbf.phar file. I noticed we can pass `--extensions=` from cli.

Thank you.

**Comment by harikt** [comment]
Actually what I was trying to do was running to make it PSR-1, PSR-2 compatible . 

It mentions method name should be camelCase  http://www.php-fig.org/psr/psr-1/#4-3-methods . But seems not fixing the same.

**Comment by aik099** [comment]
> I was trying to figure out, if there is a way to convert in phpcbf to convert the snake_case methods to camelCase. I did tried different search, but looks I didn't find what I was looking for.

There are no built-in sniffs for that. Most likely there won't such built-in sniff ever, because renaming method in a single class isn't safe way to refactor things. Writing such sniff isn't that hard:

1. find all method names in class
2. test their name to be in camel case
3. replace method name with it's fixed version

> It would be nice, if there is some documentation how to build an extension when using the phpcbf.phar file. I noticed we can pass --extensions= from cli.

The `--extensions` option is used to specify file extensions to look/fix errors in. The only way to extend PHP_CodeSniffer is through using custom sniff in your own standards.

**Comment by aik099** [comment]
You can write sniff to report wrongly named methods and then manually (e.g. in PhpStorm) rename them in a safe way.

**Comment by harikt** [comment]
@aik099 thanks for the suggestion. I understand this may not be case for every one. But the code used in one project is snake_case for method and the same library is used on another where code is camelCase ( PSR-2 ) . I wished if all is same, ie why :+1:  .

Thank you.

**Comment by gsherwood** [comment]
The reason why PHPCBF doesn't have the ability to do this is because I've made a design decision to limit core fixers to formatting changes only. Renaming methods is guaranteed to break code, and requires you to run over the entire codebase at once to be 100% sure you don't cause a naming conflict or leave old method names around, so it requires a proper refactoring tool.

**Comment by harikt** [comment]
Is there any way to add / extend the current fixer ?

**Comment by gsherwood** [comment]
> Is there any way to add / extend the current fixer ?

All fixes are done by the sniffs themselves. So you extend PHPCBF in the same way you extend PHPCS - by writing custom sniffs. When the sniffs report an error, they are told if the user wants the error fixed as well. If so, they go ahead and suggest changes that PHPCBF will later apply to the file.

And example of that is here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php#L112

**Comment by dhilst** [comment]
I tried this too, if you're using vim `tpope/vim-abolish` has this feature as a keystroke :D

**Comment by dhilst** [comment]
I forgot to place the link: https://github.com/tpope/vim-abolish :+1:
