### ISSUE TITLE
Testing XML rulesets

### ISSUE THREAD

**Issue by grappler** [squizlabs/PHP_CodeSniffer#1248]
Since version 2.7.1 I think #1177 the XML rulesets are not being tested.

What I mean is that there could be a syntax error in the XML rulesets and the unit tests would not pick it up. In my case I caught them as the code was being tested in `2.7` and `master`.

The two errors that I had in my XML ruleset were:
- Did use a closing tag for a single line rule e.g. `<rule ref="PEAR">`instead of `<rule ref="PEAR"/>`
- I renamed a sniff but forgot the change the name in ruleset.

I am not sure how this could be tested in the future but this is something that is not being tested anymore.

**Comment by gsherwood** [comment]
XML rulesets were never intentionally tested. It was an accident that they were parsed. But because they were, it meant that tests were not running in isolation (they were running with all the XML ruleset rules and exclusions applied) so they were not accurate.

The easy way to test an XML ruleset is just run PHPCS with it over a test file and confirm you get the expected output. Using something like the CSV report might make it easier to compare as well.

**Comment by grappler** [comment]
Have you thought of adding somthing like `- php scripts/phpcs -q ./README.md --standard=PHPCS` just to test the XML files.

**Comment by gsherwood** [comment]
> Have you thought of adding somthing like - php scripts/phpcs -q ./README.md --standard=PHPCS to travis just to test the XML files?

I don't think the included XML files have ever broken because I test run the standards all the time. It's typically custom coding standards that break, which wont be covered by including a travis test.

**Comment by grappler** [comment]
Ok, that fine, then I will close the issue. Thank you for your help! 😄
