### ISSUE TITLE
phpcbf 3.0RC2 crash

### ISSUE THREAD

**Issue by AJenbo** [squizlabs/PHP_CodeSniffer#1316]
Hope this is helpful

$ vendor/squizlabs/php_codesniffer/bin/phpcbf --standard=PSR2 ./skeleton/
PHP Fatal error:  Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Trying to get property of non-object in /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php on line 50 in /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Runner.php:508
Stack trace:
#0 /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Reports/Cbf.php(50): PHP_CodeSniffer\Runner->handleErrors(8, 'Trying to get p...', '/home/ajenbo/co...', 50, Array)
#1 /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Reporter.php(258): PHP_CodeSniffer\Reports\Cbf->generateFileReport(Array, Object(PHP_CodeSniffer\Files\LocalFile), false, 80)
#2 /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Runner.php(557): PHP_CodeSniffer\Reporter->cacheFileReport(Object(PHP_CodeSniffer\Files\LocalFile), Object(PHP_CodeSniffer\Config))
#3 /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Runner.php(3 in /home/ajenbo/code/frameworks/kontent/5dev/vendor/squizlabs/php_codesniffer/src/Runner.php on line 508

**Comment by gsherwood** [comment]
I can't replicate this, and it would be a fairly serious issue given the main Config object appears to not be available in this case. Is there any chance the code you are running on is available and I can test it?

If not, a few more questions:
1. Do you get this problem running PHPCS rather than PHPCBF?
2. Do you get this problem running PHPCS with `--report=diff`
3. Do you get this problem running PHPCBF over other code (maybe over the `vendor/squizlabs/php_codesniffer` folder itself)?

**Comment by AJenbo** [comment]
Turns out I was running it on the vendor folder, so probably the code is available (though I do have a couple of private packages), I'll try and see if I can narrow it down to the specific package (removing the vendor folder made it pass without issue on my code) .

**Comment by gsherwood** [comment]
Closing as there isn't anything I can do here. If you manage to find the problem code, please reopen.
