### ISSUE TITLE
PHP_Codesniffer does not have a logo

### ISSUE THREAD

**Issue by Potherca** [squizlabs/PHP_CodeSniffer#1356]
I've raised [this issue on the PEAR site](http://pear.php.net/bugs/bug.php?id=19614) in 2012 where it was closed without a response after 15 months.

Quoting my original concern:

> Description:
> ------------
> -- SHORT VERSION --
> PHP_Codesniffer currently does not have a logo. This makes it harder to "sell".
> 
> -- LONG VERSION --
> I frequently talk to people about improving their code by enforcing coding-standards on 
> their companies PHP codebase, or at the very least detecting problems. Obviously 
> PHPCS is the first tool I recommend for this task, Sadly the package does not seem to 
> have an identity of itself making it disappear into the great heap that is PEAR.
> 
> Having a logo that emphasizes PHPCS's identity would greatly help in advocating its 
> use on a broader scale.
> 
> I know this is a bit of a "non-issue", nevertheless I feel it is one that is relevant enough 
> to be raised.

Since then, various people have created their own interpretation that is being used in various places:

![code_sniffer-01](https://cloud.githubusercontent.com/assets/195757/23063307/206310fc-f50a-11e6-9d70-cf1af4ec48b2.png) ![code-sniffer-02](https://cloud.githubusercontent.com/assets/195757/23063308/20632b6e-f50a-11e6-9af5-66bb2442f666.png) ![code-sniffer-04](https://cloud.githubusercontent.com/assets/195757/23063309/2065fede-f50a-11e6-9c62-51dea08ee6c6.png) ![code-sniffer-03](https://cloud.githubusercontent.com/assets/195757/23063310/206867f0-f50a-11e6-9a94-7bff62c59117.png)

Creating further confusion.

At my current employers we have access to [a talented designer](https://www.linkedin.com/in/frankyxl) who is willing to help improve one of the existing design or create a new one (if so desired).

My question: Are any of the core developers interesting in making this happen or, if not, can we please get some sort of rational that we can point at when addressing the subject of PHPCS lacking an identifiable identity?

**Comment by gsherwood** [comment]
The main reason PHPCS doesn't have a logo because I've always got 100 more important things to be doing on this project than getting one organised.

I'm willing to bet that the vast vast majority of PHPCS users care more about the project itself improving than a logo appearing somewhere on the wiki. If this makes the project harder to "sell" for you or anyone else, that's unfortunate, but I'm comfortable with that outcome. PHPCS usage has grown completely organically over the years and I'm happy for it to continue doing so. I feel that the functionality and usage numbers of the project are a better indicator of maturity, so I don't feel like I'm in any rush to put a graphic on that identity.

Thanks for the offer of help, but a logo that a developer works under isn't something you can just get throw together, so I would have to personally be heavily involved with the design, and incredibly happy with the outcome. I work with 2 terrific product designers every day, so I would call on them to help me iterate on ideas if I was ever to create one.

I'm going to close this now that you have my response.

**Comment by Potherca** [comment]
Thanks for your response!
