### ISSUE TITLE
Non-standard exit codes in phpcbf makes it hard to integrate it

### ISSUE THREAD

**Issue by epeli** [squizlabs/PHP_CodeSniffer#1359]
Hi! 

I tried to integrate phpcbf to [neoformat (issue 54)](https://github.com/sbdchd/neoformat/issues/54) but that seems to be impossible without a wrapper script because phpcbf returns a non-zero exit status on success. In POSIX systems exit status should be zero always when the program executed as it was suposed to. More info http://stackoverflow.com/questions/1101957/are-there-any-standard-exit-status-codes-in-linux

I'd recommend that the non-standard exit codes introduced in #1270 would be moved under a flag (or just removed).

**Comment by gsherwood** [comment]
PHPCBF has several exit states and so has several exit codes. You'll need to check the exit code and decide if the script exited the way you expected because I'm not changing the current codes. They've been there in PHPCS and PHPCBF for years and checking the return value of a script is pretty easy.

**Comment by epeli** [comment]
Fair enough. I do appreciate preserving backwards compatibility. I though this was a new thing in 3.0.0RC3.

**Comment by deleugpn** [comment]
Just in case anybody else lands on this issue, the command https://github.com/squizlabs/PHP_CodeSniffer/issues/1818#issuecomment-354420927 is very helpful to start making your own workaround
