### ISSUE TITLE
AbstractSniffUnitTest::getErrorList/getWarningList parameter is not documented

### ISSUE THREAD

**Issue by PatrickRose** [squizlabs/PHP_CodeSniffer#1371]
Whenever `getError`/`WarningList` is called in the unit tests, it calls it with the name of the file being tested. This is useful, but it's not documented (granted, it's only _sometimes_ used). Would you accept a PR to update the method definition to include the test file name?

If so, where should I PR against? 3.0 or master?

**Comment by gsherwood** [comment]
The reason it is not in the method definition is because it would require every unit test to update their method definitions as well. This isn't a real problem for PHPCS tests, but it is a big BC break for those with their own unit tests.

So I would never do this in 2.x, and 3.x is too close to a stable release to drop that in as well, so I don't think I'd accept this until a 4.x version.
