### ISSUE TITLE
PSR2.Classes.PropertyDeclarationSniff.ScopeMissing is not autofixable

### ISSUE THREAD

**Issue by orlangur** [squizlabs/PHP_CodeSniffer#1372]
See
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php#L77
https://github.com/squizlabs/PHP_CodeSniffer/blob/3.0/src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php#L63

To me it looks like `public` may be inserted safely here.

Do I miss something or just not all possible autofixables of PSR2 are implemented yet? In the latter case, to avoid double work, is it safe to assume that planned work on PSR2 autofixables is finished and PRs could be proposed to cover missing cases?

**Comment by gmponos** [comment]
IMHO as a user of codesniffer I wouldn't like this to be autofixable.

You can't be really sure if the developer just forgot to add a scope on a function and initially wanted it as private.

**Comment by orlangur** [comment]
Makes sense, in such case you can disable this particular autofix or review what `phpcbf` did to your code.

But without fix this property would be `public` anyway as this is how PHP works. As for any new addition to codebase code review should occur anyway I see no problem in enabling such autofixer by default for those who just need to make a legacy codebase PSR-2 compliant with minimum manual efforts.

**Comment by gsherwood** [comment]
I didn't write fixes for every error that could possibly be fixed, but I tried to get most of them. The unit tests currently report `Tests generated 610 unique error codes; 344 were fixable (56.39%)`. So just over half are already fixable, and the other half are either not formatting issues or have not had fixers written for them.

As for this specific change, I think that adding `public` to these functions is probably not the right thing to do. Yes, it is technically still the same visibility, but it defeats the purpose of the sniff. The sniff wants you to review the method and see what the visibility should be because you've obviously forgotten to set it. Inserting `public` during normal auto-fixing will now hide the error and make it looks like a developer decided that the method should be public. But actually, the method may never have been reviewed.

So this is not an auto fix that I would accept for PHPCS. It's one of those errors that needs manual review.
