### ISSUE TITLE
Unit tests failing under PHPUnit 6.x

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#1383]
Travis has upgraded the PHPUnit version used for the PHP 7.x builds to PHPUnit 6.x.

The current testsuite is not compatible with this. This impacts both PHPCS as well as any external standards which unit test their standard using the PHPCS build in unit test mechanism.

I'm working on a fix for this.

**Comment by orlangur** [comment]
https://travis-ci.org/squizlabs/PHP_CodeSniffer/builds/209254536 shows only PHP 7.1 build failing due to `PHP Fatal error:  Class 'PHPUnit_Framework_TestSuite' not found in /home/travis/build/squizlabs/PHP_CodeSniffer/tests/TestSuite.php on line 30`

I don't like the idea of making hacks like `PHP_Codesniffer_TestsuiteWrapper` and PHPUnit version comparison to switch some implementations.

A much more reliable solution is to use PHPUnit from `vendor` folder and do not rely on Travis CI prebuilt one.

Then, it's not a problem to make testsuite compatible with both PHPUnit `5.4+` and `6.x`, such compatibility may be also enforced with proper version constraints in `composer.json` and `--prefer-lowest` as a separate Travis build env combination.

**Comment by jrfnl** [comment]
> https://travis-ci.org/squizlabs/PHP_CodeSniffer/builds/209254536 shows only PHP 7.1 build failing

Travis has since updated the PHP 7 image as well after that build was run and PHP 7 is now failing too with that same error.

> A much more reliable solution is to use PHPUnit from vendor folder and do not rely on Travis CI prebuilt one.

There are a number of reasons I went with the chosen solution rather than Composer:
* Every single external standard which uses the PHPCS test suite would have to adjust their build script for that to work. My solution is a "silent" one and their builds will just pass again.
* The Travis build for PHPCS currently does not use composer
* It would double the build time
* The PHPUnit requirements for composer are different for builds on PHP 5.2-5.3, PHP 5.4-5.6 and PHP7+.
* You can't just limit it to PHPUnit 5.x as then we'll have the same problem as soon as PHP 7.2 hits.

**Comment by orlangur** [comment]
We need any of "use phpunit from vendor" / "add some hacks" only until 
> it's not a problem to make testsuite compatible with both PHPUnit `5.4+` and `6.x`

We can fallback to PHPUnit from `vendor` only in case of incompatible version.

> and their builds will just pass again

So what? Something happening to my builds/infrastructure, but I don't care? CI is for spotting problems, not for being happy of green poorly controlled builds.

> You can't just limit it to PHPUnit 5.x as then we'll have the same problem as soon as PHP 7.2 hits.

I believe we need to check PHPUnit 5.x under PHP 7 even if Travis CI does not support it out-of-the-box.

**Comment by gsherwood** [comment]
I pushed a change to test composer install, and just to quickly get the tests running on different PHP versions. Looks like the `composer install` command takes between 20 and 30 seconds, depending on PHP version. It does get everything passing though.

**Comment by jrfnl** [comment]
@gsherwood While that works, it is - as I stated before - a plaster on the wound, not a cure. It will only delay the moment when this needs to be fixed structurally as per PR #1384.

**Comment by orlangur** [comment]
Well, if you call a couple of lines in `.travis.yml` a plaster on the wound then you miss that changes suggested in #1384 PR is not a cure but whole leg covered with plaster and bandages.

The cure is to make testsuite compatible with PHPUnit 6 without any hacks (due to forward-compatible changes introduced in PHPUnit 5.4, it is possible to make version constraint `>=5.4`).

I was really surprised when saw that builds are currently relying on builtin phpunit. It is a good thing to fix to have better control over configuration even if they would not start to fail.

As
> It would double the build time

happened to be not true I really don't see any pros in #1384 implementation approach. Actually, I don't think there would be a pro even if the "2 min 52 sec" maximum build time doubled.

Let me recheck mentioned items one-by-one to see if I'm missing something.

> Every single external standard which uses the PHPCS test suite would have to adjust their build script for that to work. My solution is a "silent" one and their builds will just pass again.

Their builds a broken currently, simple change in `.travis.yml` could be easily ported.

> The Travis build for PHPCS currently does not use composer
> It would double the build time

Irrelevant.

> The PHPUnit requirements for composer are different for builds on PHP 5.2-5.3, PHP 5.4-5.6 and PHP7+.

I don't really understand what you tried to say here. It's OK for us if any PHPUnit version installed with builtin Composer on Travis CI just works.

> You can't just limit it to PHPUnit 5.x as then we'll have the same problem as soon as PHP 7.2 hits.

I don't see which kind of problem will arise if we install PHPUnit manually. More than that, I believe it would be good to have build for each PHPUnit version with each PHP version (with respect to compatibility: no PHPUnit 6 job under PHP 5, of course).

I truly understand the feeling when you invested some time into needless implementation and then just have to abandon it. But picking the best solution let's be guided by the objective reasons.

**Comment by jrfnl** [comment]
> The cure is to make testsuite compatible with PHPUnit 6 without any hacks (due to forward-compatible changes introduced in PHPUnit 5.4, it is possible to make version constraint >=5.4).

@orlangur That would be great, though that would mean that the unit tests can no longer be run for PHP 5.1-5.5 which are explicitly supported in the PHPCS 2.x branch and PHP 5.4-5.5 for the PHPCS 3.x branch, or am I missing something ?
PHPUnit 5.x has a minimum PHP requirement of PHP 5.6 after all.

> I truly understand the feeling when you invested some time into needless implementation and then just have to abandon it. But picking the best solution let's be guided by the objective reasons.

That's not the point at all. Just like you, I'd like to see this fixed by the best solution which:
* will continue allow to unit testing for the whole range PHP versions PHPCS supports now and in the future
* preferably will allow unit testing to continue to work silently for external standards.

**Comment by orlangur** [comment]
>  that would mean that the unit tests can no longer be run for PHP 5.1-5.5 which are explicitly supported in the PHPCS 2.x branch and PHP 5.4-5.5 for the PHPCS 3.x branch

Exactly. Old PHP versions support was dropped from PHPUnit for a reason, PHPCS shall drop them at some point as well.

I'm not saying support of PHP <5.6 should be dropped in PHPCS 2.9 with testsuite adoption, it depends on roadmap. PHPCS 3.0 seems to be the best moment to drop PHP <7 support as otherwise we will have to wait for PHPCS 4.0 to drop it. But, again, it could be too early according to tool author opinion.

> allow to unit testing for the whole range PHP versions PHPCS supports now and in the future
> allow unit testing to continue to work silently for external standards

`vendor` PHPUnit solution does it too. Hacks which allow work for PHPUnit 4, 5 and 6 at the same time seems to be unnecessary to me. If we are against a cure and dropping PHPUnit <5.4 support, then such workarounds make sense to me.

**Comment by gsherwood** [comment]
> PHPCS 3.0 seems to be the best moment to drop PHP <7 support as otherwise we will have to wait for PHPCS 4.0 to drop it. But, again, it could be too early according to tool author opinion.

3.0 supports 5.4+. You can find my reasoning in the original release notes: https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.0.0a1

I can't see PHP < 7 being dropped in 4.0 either. It will depend on the state of operating systems when I get around to a 4.0. But 5.4+ support is going to be around for quite some time, so it is worth considering that in all solutions.

It is very unfortunate than PHPUnit is so aggressive with dropping older PHP version support despite a large number number of projects still having to run in corporate and government environments where the PHP versions are supported by the OS vendors under expensive SLAs. But that's the way it is. So this project will be on PHPUnit 4 for quite a while.

**Comment by orlangur** [comment]
Thanks for the information, Greg! I was not aware of significant amount of developers sticked to PHP 5.4, it reminds me the times when IE6 was quite old and hard to support but still considered for compatibility. Hope OS vendors will start to follow http://www.php.net/supported-versions.php within a couple of years.

Do you see the value in trying to be compatible with PHPUnit4, 5 and 6 at the same time?

As PHPUnit 4 [reached](https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0#end-of-life-for-phpunit-48) End of Life every next PHPUnit release can introduce more and more problems with testsuite maintenance. I see no problem in simply sticking to whatever PHPUnit version works for us.

**Comment by jrfnl** [comment]
> I was not aware of significant amount of developers sticked to PHP 5.4

One of the largest distros, CentOs, still includes 5.3.3 in their last stable release... 

To give you some idea:
* Ubuntu LTS versions: 5.3.10 (U 12.04), 5.5.9 (U 14.04), 7.0.4 (U 16.04)
* Debian main releases: 5.3.3 (D 6), 5.4.4 (D 7), 5.6.7 (D 8)
* CentOS main releases: 5.1.6 (COS 5.11), 5.3.3 (COS 6.8), 5.4.16 (COS 7-1611)

Source: http://distrowatch.com/

> Do you see the value in trying to be compatible with PHPUnit4, 5 and 6 at the same time?

I do :heart_eyes_cat: , but I presume you intended this question for @gsherwood ...

**Comment by orlangur** [comment]
> To give you some idea:

Default PHP version included does not really matter until seamless PHP upgrade is available. "large number number of projects still having to run in corporate and government environments" this usually means there is no ability to upgrade PHP or they just don't bother to due to some bureaucracy?

> you intended this question for

For anyone actually, why make things harder trying to use them the way they are not intended to be used :)

**Comment by gsherwood** [comment]
Closing this so commenting can be kept in one location. I think it's best to kept it on the PR where the difference between a BC fix and a composer fix can be specifically discussed.
