### ISSUE TITLE
-vv mode uses colors, even with --no-colors specified

### ISSUE THREAD

**Issue by ExplodingCabbage** [squizlabs/PHP_CodeSniffer#1386]
Whitespace tokens still get printed in greeny-grey. See screenshots:

![image](https://cloud.githubusercontent.com/assets/2358339/23833052/31581cf0-0738-11e7-8f79-12070e5a314c.png)
![image](https://cloud.githubusercontent.com/assets/2358339/23833058/44248972-0738-11e7-9ce0-943b46c516fe.png)

Wouldn't it be helpful for explicitly specifying `--no-colors` to suppress colored output, even in `-vv` mode?

(This behaviour is why my copy of output in https://github.com/squizlabs/PHP_CodeSniffer/issues/1385#issue-213611285 has a load of garbled color codes in it.)

**Comment by jrfnl** [comment]
Related #1352 ?

**Comment by gsherwood** [comment]
> Related #1352 ?

Not in this case. I added colours to the verbose output separately from the coloured report output, so the verbose output doesn't use the CLI settings for this.

The main reason is that the verbose output is sent directly to screen as each line is processed, from all over PHPCS, so that output is seen as quickly as possible. Reports are buffered and I strip the colour codes from them all in one go, just before outputting.

This change is a good idea, but I'd need to write a wrapper function for outputting to screen and then strip the colour codes output inside there if required. So that means changing quite a few places.

But to be honest, this is going to be pretty low priority for me due to time constraints.

**Comment by gsherwood** [comment]
Closing as I can't see myself ever getting around to this, and it's just in debug output.
