### ISSUE TITLE
--config-set installed_paths overwrites itself

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#1436]
phpcs 2.8.1
attempted 
```php
phpcs --config-set installed_paths /path/to/one
phpcs --config-set installed_paths /path/to/two
```
### result
only `/path/to/two` was added to the installed_paths

### expected
both `/path/to/one` and `/path/to/two` should be added to the installed_paths. 

### note
`phpcs --config-set installed_paths /path/to/one,/path/to/two` will add both to the installed_paths. but in the other case it's unexpected to lose  `/path/to/one` by using a second call to `--config-set`

**Comment by gsherwood** [comment]
I take your point, but this is working as expected and I don't intend to make any changes to it at this time.

The config settings are single values and the config-set and config-delete commands act on an entire config value at once.

If config-set added sub-values to a config value instead of overwriting it, I'd need to provide a new command that allowed you to remove those sub-values because config-delete wipes the entire config value. This fundamentally changes how config values are represented as I would now have a special type of config value that accepts (presumably) an array.

**Comment by photodude** [comment]
I'm looking at it from the case of installing multiple coding standards where each coding standard uses the composer scripts post-install to run config-set. 

With the current way the config-set works in this case only the last installed coding standard would be installed. 

I can understand if it's low priority but I believe this would be a good improvement.

**Comment by jrfnl** [comment]
AFAIK Composer [will not run scripts from dependencies](https://getcomposer.org/doc/articles/scripts.md#what-is-a-script-).
The main project has to define it's own script to set the `installed_paths` config variable and can do so for all standards pulled in as dependencies in one go.

**Comment by photodude** [comment]
As you mentioned, if the package was installed as global the scripts would run. Which would cause the case of multiple coding standards overwriting the `--config-set installed_paths`

**Comment by jrfnl** [comment]
@photodude You may want to have a look at the [phpcodesniffer-composer-installer](https://github.com/DealerDirect/phpcodesniffer-composer-installer) for Composer and at the question about this which I asked them: https://github.com/DealerDirect/phpcodesniffer-composer-installer/issues/24

**Comment by gsherwood** [comment]
Closing as nothing has happened with this proposal. Keeping config-set the same for all config values is still preferred at this time.
