### ISSUE TITLE
Extend a common standard

### ISSUE THREAD

**Issue by jameskraus** [squizlabs/PHP_CodeSniffer#1483]
Is there an easy way to extend a common standard, like PSR-2? Something I love about eslint is how easy it is to just take an existing standard and add your own tweaks. Is there an equivalent with PHPCS? If not, can we make one?

e.g. Adding something like this to a standard file:
``` <rule ref="psr-2"/>```
or
``` <standard ref="psr-2"/>```

**Comment by gsherwood** [comment]
Standards are extended using the ruleset.xml format. It is explained here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

Here is an example a few people use, which is PSR2 with tabs used for indenting instead of spaces: https://gist.github.com/gsherwood/9d22f634c57f990a7c64

And here is a phpcs.xml file that PHPCS itself uses to define it's coding standard (it also sets some CLI values and default files and folders to check): https://github.com/squizlabs/PHP_CodeSniffer/blob/master/phpcs.xml.dist

Is this what you are after?

**Comment by jameskraus** [comment]
Exactly, thank you!

**Comment by gsherwood** [comment]
You're welcome
