### ISSUE TITLE
Update Wiki with documentation about DoubleQuoteUsage sniff

### ISSUE THREAD

**Issue by maltzj** [squizlabs/PHP_CodeSniffer#1485]
Right now the wiki does not have a comprehensive list of the available sniffs.  This adds one that we're using at Eat24.  Here's a txt of the updated file (github won't let me add `.md` files :\ )

[Customisable-Sniff-Properties.txt](https://github.com/squizlabs/PHP_CodeSniffer/files/1026683/Customisable-Sniff-Properties.txt)

**Comment by jrfnl** [comment]
Note: The list you tried to update **_only_** contains sniffs which have customizable properties. The sniff you've added does **not** have any customizable properties and therefore does not belong in the list.

I'm not sure what would be a better place for it. For me, only the PEAR developer documentation comes to mind and the sniff *is* documented there: http://pear.php.net/package/PHP_CodeSniffer/docs/latest/

**Comment by maltzj** [comment]
Oh, thanks for that super helpful context!  Right now the project links to the github wiki as the source of documentation, so I never thought to look at the PEAR documentation, and probably would've considered it out of date even if I found it :\.  

If the plan is to use PEAR docs as canonical for now, what do you think about linking relevant sections from the github wiki so that they're more discoverable?  Alternatively, it looks like the documentation is PEAR is autogenerated.  Is there any way to do the same for the github wiki?

**Comment by jrfnl** [comment]
@maltzj There are two types of documentation which - in this case - actually overlap each other a bit:
* End-user documentation, i.e. for someone who uses PHPCS and maybe has a custom ruleset. That documentation *used* to be on PEAR, but has since moved to the wiki here.
* Technical documentation, this documentation is (mainly) intended more for sniff developers and is the one I pointed you to. It is still hosted on PEAR and actually completely up-to-date. Documentation is available for all releases and yes, as far as I know, it is auto-generated from the source code using PHPDocumentor or a PEAR-specific variant of that.

The wiki documentation is not auto-generated and cannot be with how GH works with wiki pages - quite apart from that info not being available anywhere else -.

> If the plan is to use PEAR docs as canonical for now, what do you think about linking relevant sections from the github wiki so that they're more discoverable?

For this suggestion, I defer to @gsherwood

**Comment by gsherwood** [comment]
No, the wiki does not have a comprehensive list of sniffs and what they do. If you want to see what sniffs are within PHPCS, you'll currently have to browse the code.

Some sniffs do have documentation in a Docs folder, and my plan was to increase that documentation so that PHPCS could use it when generating docs (that's the `--generator` CLI option) but I haven't been able to find time for that. Someone people have submitted PRs to increase those docs in the past, but few people focus on that part of the product.

If you'd like to increase basic sniff documentation, I'd be happy to review PRs that add to the current Docs folder. Here is an example doc to make sure it's clear what I'm talking about: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Docs/ControlStructures/InlineControlStructureStandard.xml

> If the plan is to use PEAR docs as canonical for now, what do you think about linking relevant sections from the github wiki so that they're more discoverable?

Those docs are auto-generated and I don't expect anyone to ever look at them. I've got no plans to bring these into the wiki or make them the source of truth for anything.

**Comment by jrfnl** [comment]
> I don't expect anyone to ever look at them.

@gsherwood Just FYI: I actually use them regularly, especially when making sniffs cross-PHPCS-version compatible ;-)

**Comment by gsherwood** [comment]
> Just FYI: I actually use them regularly

Expect the unexpected :)

**Comment by maltzj** [comment]
So it sounds like the move here is "Add docs to the `docs` directory and refer to the PEAR docs for a comprehensive list of sniffs until something better comes along?"

**Comment by gsherwood** [comment]
> So it sounds like the move here is "Add docs to the docs directory and refer to the PEAR docs for a comprehensive list of sniffs until something better comes along?"

Sure
