### ISSUE TITLE
*Actually* fixing errors automatically is made impossible by `phpcs --report=diff`'s code

### ISSUE THREAD

**Issue by wimleers** [squizlabs/PHP_CodeSniffer#1486]
The problem is:
```
diff -u -L\"$filename\" -LPHP_CodeSniffer \"$filename\" \"$fixedFile\"";
```

(in `src/Fixer.php`)

`phpcs` is labeling the source with the actual file path. But the target `phpcs` hardcodes to `PHP_CodeSniffer`. Which is why it's *impossible* to actually apply the patch. At least… it's impossible to apply it non-interactively.

The docs at https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically say:
```
$ patch -p0 -ui /path/to/changes.diff
patching file /path/to/code/file.php
```

But the reality is this:
```
$ patch -p0 -ui codesniffer_fixes.patch 
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- modules/media/src/Plugin/media/Source/File.php
|+++ PHP_CodeSniffer
--------------------------
File to patch: 
```

---

Given the comment at https://github.com/squizlabs/PHP_CodeSniffer/issues/286#issuecomment-58982362, I believe this may be intentional. @gsherwood wrote:
> I personally want to hand-create every diff file I commit to the core because it forces me to think about how the fix is being applied and what other sniffs might have issues with it. But thanks for sharing the script, and it's obviously working well for you.

The solution is trivial: set both the first and the second label `-L\"$filename\"`.

But the docs at https://github.com/squizlabs/PHP_CodeSniffer/wiki/Fixing-Errors-Automatically suggest it actually _should_ be working. So… this is rather confusing.

---

This has existed since `--report=diff` was introduced in https://github.com/squizlabs/PHP_CodeSniffer/commit/e2688387f5c13c792cbbf51afb179d8b6308ae26.

**Comment by wimleers** [comment]
We found the root cause for our problems; we got it working. But I think it'd still be good to change this. This is still a WTF for people familiar who use patches daily.

**Comment by gsherwood** [comment]
The goal of the diff report is to show the difference between the file as it exists and the file as PHPCS thinks it should be. I used the PHP_CodeSniffer label to make it clear which is which, especially for people who don't use patches daily.

I've never had any problem applying these patches, and the diff report has been like this since it was introduced just over 3 years ago. PHPCBF also used it to apply patches (it used `patch` before version 3) for that entire time without any reported problems, so I think the format is fine.

> Given the comment at #286 (comment), I believe this may be intentional.

I just wanted to point out that this comment is unrelated to your point (it's to do with testing the auto-fixing system) and was even posted after the diff report (and PHPCBF auto-fixing) were released.

**Comment by wimleers** [comment]
FYI: We had two people staring at the `patch` command and didn't spot the problem. Eventually we did. It's ridiculously silly: we're used to doing `patch -pN < patchfile`. So we assumed that the `-ui` was just another flag. But apparently `-i` changes the default behavior, so that the patch is no longer read from `stdin`.

IOW: the DX of `patch`'s parameters is a huge WTF.

Conclusion:

1. `phpcs` is weird for pretending the target is `PHP_CodeSniffer`, which causes `git apply` to completely choke on it
2. … but using `patch`, you can actually still apply it
3. `patch` is weird
