### ISSUE TITLE
CSS and JS in other file doesn't check

### ISSUE THREAD

**Issue by josephzidell** [squizlabs/PHP_CodeSniffer#1500]
The CSS and JS tokenizers work fine on `.css` and `.js` files respectively. However, if I have a mixed file with PHP, JS and CSS, only the PHP is recognized and checked.

I am using the typical tags

    <script type="text/javascript">...</script>

and

    <style>...</style>

**Comment by gsherwood** [comment]
Yes, that's correct. There is no HTML tokenizer for PHP_CodeSniffer so it is unable to look into the content outside PHP tags (PHP considers this HTML content) and check that.

It is also a problem when the CSS or JS may also contain PHP, and possibly be broken up over several PHP blocks. There is no way to stitch those together and get a complete picture of what the contents would look like using only static analysis. Yes, there are plenty of examples where it would work fine, but there are also plenty of examples where it would break, and those are the ones that I'll hear about via bug reports.

So in general, you'd need to structure your application so CSS and JS is included into templates as required. This will allow PHPCS to check those files independently. If you don't want to structure your application like that, PHPCS will not be able to check the content.

I'm closing this because this isn't a feature I think is possible to achieve with a good level of accuracy, so I don't want to leave it open and have people think it is on the roadmap. But thanks for getting in touch anyway, even if this isn't a feature I think I can add.

**Comment by josephzidell** [comment]
Good point. It would be better to have the JS in its own files. This issue actually triggered a good discussion on our team about code structuring.

Thanks!

**Comment by gsherwood** [comment]
Glad to hear it. Hope you are able to work something out, and thanks for getting back to me.
