### ISSUE TITLE
Code sniffer is creating a warning 'Variable $promise is undefined.'

### ISSUE THREAD

**Issue by pwaterz** [squizlabs/PHP_CodeSniffer#1517]
```
$promise = new Promise(function () use (&$promise, $http_promise) {
        $resp = $http_promise->wait();
        $policy = new ExtractPolicy(strval($resp->getBody()));
        $hw_response = new HWResponse($resp, $policy);
        $promise->resolve($hw_response);
    });
```
Code sniffer is saying

```
Variable $promise is undefined.
```

Why?

**Comment by gsherwood** [comment]
The sniffs included with PHP_CodeSniffer do not have any checks for undefined variables, so that error is probably not coming from PHP_CodeSniffer itself.

Are you using a custom coding standard? Can you run `phpcs` with the `-s` command line option and have a look at the error code that appears next to that error message? That will tell me which sniff the error is being generated from.

**Comment by pwaterz** [comment]
I'm using the drupal and drupal standards sniffs. I'll take the issue up there. Thank you for your time.
