### ISSUE TITLE
[--runtime-set key value] not working

### ISSUE THREAD

**Issue by OwnerOfThisIsle** [squizlabs/PHP_CodeSniffer#1529]
I use a plugin in my IDE to run phpcs.
It uses the following parameters:
`phpcs --runtime-set default_standard PSR2`

In phpcs version 2.8 this switched from a default standard to PSR2, for instance I got different output when calling
`phpcs --runtime-set default_standard PSR2 -e`
and
`phpcs -e`

I updated phpcs using composer (3.0.0 and 3.0.1) and after that
the --runtime-set Option seems to be broken, because now both commands from above output the same result.

Additional note:
`phpcs --runtime-set default_standard wrongname -e` 
led to an error, in the 2.8 version, but is silently ignored now.

**Comment by gsherwood** [comment]
`--runtime-set` is definitely working because I'm using it to set sniff debug settings. But I'll have a look at what might be happening when trying to set the default standard using runtime settings.

In case you are not aware, the way to set the standard you want for checking is to use the `--standard` command line argument.

If you want PSR2, you'd use: `phpcs --standard=PSR2 /path/to/code`

The default standard is only used when PHPCS can't figure out what standard you want because nothing was on the command line, nothing is set in your config vars, and no phpcs.xml files have been found anywhere. It's not an accurate way of ensuring your code is always using the standard you want.

**Comment by gsherwood** [comment]
Yes, I've confirmed that using `--runtime-set` to set things like the standard/report/report-width to use worked in 2.9 due to a quirk in the way CLI values were processed. This has been refactor in 3.0 to ensure a consistent order of overriding (CLI overrides everything) and you can no longer use `--runtime-set` to set values for things that already have dedicated CLI values.

Hopefully you'll be able to use the `--standard` command line argument to run PHPCS with the PSR2 standard as this is the supported way of choosing a coding standard.

**Comment by OwnerOfThisIsle** [comment]
In the meantime I found out that the netbeans plugin phpcsmd is using the --standard parameter and can be used as a workaround.

But Netbeans itself, that ships with the INSPECT Feature, and allows to configure Codesniffer in Tools->Options->PHP->Code Analysis depends on the 2.8 "quirk".

Maybe I should tell them, but I ve not fully understood why the --runtime-set function is not doing anything with "default standard" even when no CLI param --standard is set. (And no phpcs.xml is found.)
What still looks like a bug, is that although I set a default, it falls back to some other hardcoded(?) default.

**Comment by gsherwood** [comment]
> Maybe I should tell them

That would be great if you could report an issue there. The change should be quite easy (replace the runtime-set commands with their CLI equivalents) and it is completely backwards and forwards compatible.

> but I ve not fully understood why the --runtime-set function is not doing anything with "default standard" even when no CLI param --standard is set

Simply because it was never coded to do that. The fact that it did was just because of code execution order, and that execution order has completely changed in 3.0. I could probably restore the ability to use runtime-set instead of the proper CLI args, but that would make the code worse for no actual benefit.

I'm going to close this issue now as you've got a workaround, I've identified that there is a difference between versions, but I'm not going to make any code changes.

What I will do is fix the documentation of PHPCS to make it clear what runtime-set is actually for because I was a bit lazy when writing those docs originally.

Thanks for letting me know about this and hope you're able to open an issue with Netbeans and have it resolved in there.

**Comment by gsherwood** [comment]
Docs updated here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#setting-configuration-options

Config options now also tell you which CLI arg to use here: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options
