### ISSUE TITLE
Forcing the autoload of the composer to happen before the expected moment.

### ISSUE THREAD

**Issue by elvishp2006** [squizlabs/PHP_CodeSniffer#1668]
This code snippet in the **load** function of **autoload.php** is forcing the autoload of the composer vendors before the expected moment:
```php
if (strpos(__DIR__, 'phar://') !== 0
	&& file_exists(__DIR__.'/../../autoload.php') === true
) {
	self::$composerAutoloader = include __DIR__.'/../../autoload.php';
	if (self::$composerAutoloader instanceof \Composer\Autoload\ClassLoader) {
		self::$composerAutoloader->unregister();
		self::$composerAutoloader->register();
	} else {
		// Something went wrong, so keep going without the autoloader
		// although namespaced sniffs might error.
		self::$composerAutoloader = false;
	}
} else {
	self::$composerAutoloader = false;
}
```
I'm using PHP_CodeSniffer as **require-dev** inside my project.

**Comment by gsherwood** [comment]
Are you able to provide some information about what problem you are seeing, what is not working, and some steps to replicate?

**Comment by elvishp2006** [comment]
Ok I'm using it on a WordPress theme, I have anothers required libs with composer, like https://github.com/TGMPA/TGM-Plugin-Activation 
I include the autoload.php of composer inside the functions.php, at this moment all the WordPress aplication was loaded, and all libs that use WordPress functions is working fine.
But if I try to execute the phpcs its rise a exception because it loaded the tgmpa lib before the WordPress was loaded. This is the cenario

**Comment by jrfnl** [comment]
@elvishp2006 AFAICS this is not a PHPCS issue, but one of using TGMPA in combination with Composer autoload. This issue was solved in https://github.com/TGMPA/TGM-Plugin-Activation/pull/665 and will be included in the next release of TGMPA.

**Comment by elvishp2006** [comment]
@jrfnl I've just used this lib as an example, but there are others with the same behavior, and I think this is not a problem with these libs because they are doing nothing wrong, they are just being forced to load before even basic WordPress. Why does phpcs need to force autoload to occur? and that a global installation of phpcs does not have this behavior?

**Comment by jrfnl** [comment]
@elvishp2006 PHPCS is however not autoloading your classes, just registering the autoloader to find them (if needed).
If your project is force autoloading all classes as soon as the autoloader is registered, there might be something in the Composer configuration which should be changed.

**Comment by elvishp2006** [comment]
@jrfnl This is the point, I think phpcs should not do this, for what reason is it registering autoload.php? What is the purpose of this? as I said before, phpcs installed globally does not do that.

**Comment by jrfnl** [comment]
@elvishp2006 Except PHPCS does not do so. It only registers the autoloader, it does not load the classes (except for the ones it needs).

> for what reason is it registering autoload.php? What is the purpose of this? 

It does so to aid in loading arbitrary files for external standards. Think abstract sniff classes used as a base class in an external standard.

> as I said before, phpcs installed globally does not do that.

PHPCS installed globally registers the autoloader just as well (if available), except won't have *your* project dependencies included in the autoload file which is why you're not seeing the same behaviour.

**Comment by elvishp2006** [comment]
Many libs made for WordPress have in their first line the following code:

```php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
```

This is a very common feature of projects developed for WordPress, and many of these libs do not have autoload, so you need to do the following in composer.json to load the file:

```json
    "autoload": {
        "files": [
            "vendor/path/file.php"
        ]
    }
```

And when phpcs register the composer autoload it goes to hit the ABSPATH check, which will terminate the application.

What would be a solution to do without the need to change all these libs?

**Comment by jrfnl** [comment]
> This is a very common feature of projects developed for WordPress

@elvishp2006 And that's what the problem stems from: WordPress, as it is, is not typically suitable for combining with Composer. That is an issue with how WordPress has grown historically, not a PHPCS issue.
It is your Composer file causing the problem by autoloading the `files`, not PHPCS.

Just off the top of my head there are a couple of thing you could try, but as I said: not an PHPCS issue:
* Have you looked at [`autoload-dev` for Composer](https://getcomposer.org/doc/04-schema.md#autoload-dev) ? Would that help you ?
* What about using a `classmap` instead for Composer instead of hard including the files ? See: https://getcomposer.org/doc/04-schema.md#autoload
* A typical change to be a bit more Composer friendly for WP related projects is to change the code sample you gave to:
```php
if ( ! defined( 'ABSPATH' ) ) {
	return;
}
```
That does mean that those files will still need to be hard included again at the point they are actually needed, which goes against the principle of autoload, but that's how it is for WP projects.
