### ISSUE TITLE
Report only issues discovered within a given `diff`

### ISSUE THREAD

**Issue by Ocramius** [squizlabs/PHP_CodeSniffer#1680]
This is the same as https://github.com/squizlabs/PHP_CodeSniffer/issues/678, but with added context.

Specifically, the possible approach could be following

 1. scan entire files/project (as currently happens)
 2. provide CS checks for that (as currently happens)
 3. report *only* CS issues on tokens that are within the `diff` report (custom report tool?)

Thoughts? Can PHPCBF also be adapted for that, or are we shooting too far?

The idea is that we can run this stuff in CI for post-merge commits :-)

**Comment by jrfnl** [comment]
Left some suggestions in the twitter thread about the same: https://twitter.com/Ocramius/status/913669597819211776 Hope it helps.

PHPCS 3.x allows for building your own filters as well. It ships with a `gitmodified` filter, but you can create your own and might be worth pulling it here ;-)

**Comment by exussum12** [comment]
Look at https://github.com/exussum12/coverageChecker

It's designed to work with many tools. Phpcs being one of them

**Comment by gsherwood** [comment]
> That will only fail if the line appears in both the report and the diff

That's typically not good enough for PHPCS sniffs. Some checks, like the PSR1 side effects sniff, process the entire file at once and then report an error on line 1. If you didn't change the first line in your file, then these errors wouldn't appear in your report.

The only way to truely know what new errors were introduced by a diff is to find the modified file, run PHPCS over them without your changes, run PHPCS over them with your changes applied, and then diff the report output. This will tell you what new errors you introduced, including any that were reported for the entire file.

**Comment by exussum12** [comment]
Ah ok I can add that to the check, Are there any more sniffs like that ?

In the majority of cases this works, and hopefully in that case code review would pick up that error (even if this tool missed it)

**Comment by gsherwood** [comment]
> Are there any more sniffs like that ?

There are, but I can't remember them all off the top of my head. I know the Generic.Files.LineEndings sniff does, but I know there are others.

Also, it's not just a problem for sniffs that report an error on the first line. Some sniffs are going to complain about things like a code structure now getting too long, or a function comment not including a new thrown exception type. These errors are reported on things like the IF, FORECH, FUNCTION, and function comment tokens. You probably didn't change these lines to cause the error, but you've now made the entire code block or comment invalid in some way so that's where the error is reported. But if you didn't change these lines, you wont see that new error.

**Comment by exussum12** [comment]
Ah ok. I have been using phpmd for these checks. Their report gives a range of lines so for example the class getting g too big includes the entire class definition.

Would it be possible to add a line_start and ljne_end to this report ? It shouldn't break BC as line will still be available ? 

Happy to send the pr during the week if this would be ok

**Comment by exussum12** [comment]
I have added the two sniffs you have mentioned to match a whole file instead of lines.

From what I can see it would be changing the addError function to accept either an int (current behaviour) or an array / object containing the start / end of the function.

Would that be an OK change for me to make ?

**Comment by gsherwood** [comment]
> Would it be possible to add a line_start and ljne_end to this report ? It shouldn't break BC as line will still be available ?

That would be a pretty significant change to how PHPCS reports issues. I think it may make things quite confusing when it comes to reporting as well.

I don't think I'd accept a PR for that, but would be happy to hear ideas for the version 4 release. It would need to help improve more than just the coverageChecker tool though, and I'm not sure how it would make the built-in reports any better, or how IDE integrations could make use of it.

**Comment by gsherwood** [comment]
Closing due to lack of interest and complexity

**Comment by jrfnl** [comment]
Loosely related #2137
