### ISSUE TITLE
Docblock about stack pointer on interface explanation

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1748]
Hello, inside the `Sniff` Interface on function `process`.

> Return (count($tokens) + 1) to skip the rest of the file

Can you please specify what this means and maybe even better with an example? Where is this needed or where should this be avoided? I have checked inside the package and I don't think I have found another sniff returning this.

**Comment by gsherwood** [comment]
Here is an example: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/Files/LineLengthSniff.php

This sniff listens for open tags, on which there can be many in a file. So after it kicks in to process the first one, it goes through and processes the whole file. Having the sniff re-loaded for each subsequent open tag in the file would be a waste because the whole file has already been processed, so it tells PHPCS to ignore this sniff until it hits a specific token position, which is after the EOF.

There are several others that use this exact trick. The ones that come to mind are:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/WhiteSpace/DisallowTabIndentSniff.php
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/WhiteSpace/DisallowSpaceIndentSniff.php
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php

Sniffs don't have to return the last token in a file though. You can also use this return value to pause this sniff until, for example, the end of the function or class you started checking. I've used this in custom sniffs but I can't remember if any of the included sniffs are doing this.

Does that info help?

**Comment by gmponos** [comment]
>  I don't think I have found another sniff returning this

Ah.. sorry, I was searching for  `(count($tokens) + 1)` but you had it as `($phpcsFile->numTokens + 1)`

Anyway if I remember correctly phpcbf may pass over a file several times in order to fix it. If a sniff returns this is it possible it may cause the sniff not to repass again?

**Comment by gsherwood** [comment]
> Anyway if I remember correctly phpcbf may pass over a file several times in order to fix it. If a sniff returns this is it possible it may cause the sniff not to repass again?

Yes, it makes multiple passes over a file, but it resets the file each time (the content has changed after each pass) and every sniff gets a chance to run over the file again. On that next run, the token numbers have typically changed as well (because of the file content change) so that return value isn't important any more.
