### ISSUE TITLE
Generic.Arrays.ArrayIndent and + with function

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1798]
Hello I have the following code:

``` php
        } catch (Exception $e) {
            $data= $e->getData() + [
                    'key' => 'value',
                    'key2' => 'value2',
                ];
        }
```

```
 186 | ERROR | [x] Array key not indented correctly; expected 16 spaces but found 20 (Generic.Arrays.ArrayIndent.KeyIncorrect)
 187 | ERROR | [x] Array key not indented correctly; expected 16 spaces but found 20 (Generic.Arrays.ArrayIndent.KeyIncorrect)
 188 | ERROR | [x] Array close brace not indented correctly; expected 12 spaces but found 16 (Generic.Arrays.ArrayIndent.CloseBraceIncorrect)
```

I am not sure if this is a problem of Codesniffer or problem of PhpStorm because this is the indentation used by PhpStorm autofix. If this is an issue of PhpStorm does it happen to know a work around?

**Comment by gsherwood** [comment]
If you want to indent your code like that, you can't use the new `Generic.Arrays.ArrayIndent` sniff because it wants the array indent one tab stop and not 2. I'm not sure why PHPStorm would position the closing array bracket where it has - it seems quite random.

If you want PHPStorm to format your code one tab stop, you might have to ask on their forums. I have no experience with it.

**Comment by gmponos** [comment]
It seems that this is a bug of PHPStorm... Please vote

https://youtrack.jetbrains.com/issue/WI-36662

https://twitter.com/gmponos/status/942693578454601734

**Comment by gmponos** [comment]
It seems that the issue I posted from youtrack is unrelated but never the less I believe that the issue is not related to codesniffer.
