### ISSUE TITLE
Squiz.WhiteSpace.MemberVarSpacing spacingBeforeFirst not working

### ISSUE THREAD

**Issue by oojacoboo** [squizlabs/PHP_CodeSniffer#1802]
The `spacingBeforeFirst` property for the `Squiz.WhiteSpace.MemberVarSpacing` sniff is not working in the following example.

```
<rule ref="Squiz.WhiteSpace.MemberVarSpacing">
    <exclude name="Squiz.WhiteSpace.MemberVarSpacing.FirstIncorrect" />
    <properties>
        <property name="spacingBeforeFirst" value="2" /> <!-- not working -->
        <property name="spacing" value="1" />
    </properties>
</rule>
```

```php
<?php

class Foo
{

    use Bar;

    /** @var string */
    protected $baz;
}
```

Additionally, I had to exclude the error for `Squiz.WhiteSpace.MemberVarSpacing.FirstIncorrect` because, without the `use` statement, it's expecting the actual value of `spacingBeforeFirst`.

**Comment by gsherwood** [comment]
This is because the sniff determines that a member var is the first member var if it is the first content after the opening brace of the class/interface/trait. You've put a use statement in there, so it's just treating the member var as a normal code block.

The intention of the "first" member var rule is really to ensure you can reduce padding between the opening brace of the class and the first member var comment. It was never designed to expect code to be sitting in that area, or else it probably would have been called "spacingAfterBrace".

> Additionally, I had to exclude the error for Squiz.WhiteSpace.MemberVarSpacing.FirstIncorrect because, without the use statement, it's expecting the actual value of spacingBeforeFirst.

I'm not sure what you're saying here. When you remove the `use` statement, the sniff now detects the member var as the first, and ensures there are 2 blank lines before it, as per your ruleset. You don't need to exclude the error; you need to set the `spacingBeforeFirst` property to be the value you want. If you don't want 2 blank lines, set it to 1. If you don't want it to check padding at all, then exclude it.

**Comment by jrfnl** [comment]
FYI: there is a related PR - #1721 - open which documents the existing behaviour of classes containing traits with unit tests and also contains a fix for multi-property declarations.

**Comment by oojacoboo** [comment]
Well, maybe it needs to be updated to be `spacingAfterBrace`, because as it's currently named, it's not very clear.

As for my second issue with excluding `Squiz.WhiteSpace.MemberVarSpacing.FirstIncorrect` now makes sense because it's actually working.  The thing is, only want 1 line after an opening brace, but 2 lines if there are `use` statements before the first member var and 1 line between member variables.  I cannot seem to be able to accomplish this.

```
<?php

class Foo
{

    use Bar;


    /** @var string */
    protected $baz;

    /** @var int */
    protected $num;
}
```

**Comment by gsherwood** [comment]
> Well, maybe it needs to be updated to be spacingAfterBrace, because as it's currently named, it's not very clear.

Maybe, but I'm not going to change it as it would be a big BC break.

> The thing is, only want 1 line after an opening brace, but 2 lines if there are use statements before the first member var and 1 line between member variables. I cannot seem to be able to accomplish this.

The sniff doesn't support a setup like this. None of the included sniffs do, so you'd have to write your own if you want a rule like this because it looks pretty custom.
