### ISSUE TITLE
try/catch 

### ISSUE THREAD

**Issue by KayakinKoder** [squizlabs/PHP_CodeSniffer#1857]
PSR 2 should require that `catch` be on the same line as the closing `}` of `try`. If a comment is accidentally added after the closing `}` as below, we don't see an error.

```
try {
    $x = 1;
} // stray comment here
catch (Exception $exception) {
    $x = 2;
}
```

Is this expected behavior?

**Comment by gsherwood** [comment]
This is intentional as PHP-FIG decided that comments could go wherever you wanted, and can be indented however you like, because PSR-2 explicitly says comments are ignored. This leads to some pretty ugly code.

But I've looked through PSR-2 again and there is this bit about IF/ELSE/ELSEIF and highlighted an important note:
> An if structure looks like the following. Note the placement of parentheses, spaces, and braces; **and that else and elseif are on the same line as the closing brace from the earlier body**.
> ```
> <?php
> if ($expr1) {
>     // if body
> } elseif ($expr2) {
>     // elseif body
> } else {
>     // else body;
> }
> ```

Technically, this does not apply to TRY/CATCH and DO/WHILE because those are different sections. But I suspect the authors just didn't repeat themselves because they didn't think it was necessary. So maybe this is enough to change the PSR-2 rules to enforce the placement of comments in control structure blocks.

**Comment by KayakinKoder** [comment]
Thanks for the info, I hope that is something they would want to enforce. It seems to me that some of these loose-y rules were written because many large existing projects wouldn't be able to pass stricter rules. I think that very strict style rules with the ability to turn each specific rule off, while you update your codebase to conform to the rule, is a better way to go.

**Comment by KayakinKoder** [comment]
Just noticed you added this to a milestone so I'll leave it open

**Comment by gsherwood** [comment]
I've added a new sniff to enforce this rule.

**Comment by jrfnl** [comment]
@gsherwood By the looks of it, there was already a sniff in place for this, which just needs a small bugfix - see #1929
