### ISSUE TITLE
Standard/Ruleset over HTTP

### ISSUE THREAD

**Issue by smsalisbury** [squizlabs/PHP_CodeSniffer#1872]
It would be nice to be able to load a ruleset over HTTP(S). For example, if I wanted everyone in my organization to follow certain coding standards, I could serve up a file at `https://www.myorganization.com/phpcs/ruleset.xml`. Then developers in my organization could use that file like:

```
$ phpcs --standard=https://www.myorganization.com/phpcs/ruleset.xml file.php
```

Right now if you do this you get a `the coding standard is not installed` error.

Are there any reservations about this? If not, I'll go ahead and begin working on a pull request.

**Comment by gsherwood** [comment]
I don't think I'd recommend people grab rulesets remotely, but I can't see how one could really pose any security issues.

I imagine the next thing someone would ask for would be for the file to be cached, which then leads to issues with cache invalidation of the remote ruleset. People obviously need to keep working in their connection goes down, so we'd need to consider that, and the timeout length to ensure runs don't wait ages to start in these cases.

If you want to have a think about these sort of things, I'd be happy to have a conversation about them and eventually review a PR.

**Comment by spencer4of6** [comment]
I can't think of any security issues off the top of my head either, although https would definately be preferable to http. We can consider showing a warning if http is used instead of https.

As far as caching goes, we could retrieve the `ruleset.xml` file and cache it on their local machine (either as-is or as a serialized `Ruleset` object). I'd imagine we'd prioritize using the remote file, and then after a relatively short timeout period default to the cached version and display a message letting the user know that the cached version is being used.

**Comment by gsherwood** [comment]
I've decided that this isn't a feature I want to support in PHPCS at this time, so I'm going to close this issue. I haven't received any additional requests for this functionality and I don't want to open PHPCS up to any additional security issues.
