### ISSUE TITLE
Exclude then re-include example in Annoted-ruleset does not work

### ISSUE THREAD

**Issue by tdmalone** [squizlabs/PHP_CodeSniffer#1917]
It appears that re-including a specific sniff - after excluding a whole standard - is being ignored by PHPCS. At first I thought I had the config wrong when doing this with other sniffs, but I've since tried it with the direct example from [Annotated-ruleset.xml](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml) (press Ctrl+F and search for 'commenting.todo' to find the part of the example I'm lifting from).

To replicate:

_test.php:_
```
<?php
// TODO: Test.
```

_phpcs.xml:_
```
<?xml version="1.0"?>
<ruleset>
 <rule ref="Squiz">
  <exclude name="Generic"/>
 </rule>
 <rule ref="Generic.Commenting.Todo"/>
</ruleset>
```

_Expected output:_
```
$ phpcs -s test.php

FILE: ...\test.php
------------------------------------------------------------------------------------------------------------
FOUND 2 ERRORS AND 1 WARNING AFFECTING 2 LINES
------------------------------------------------------------------------------------------------------------
 2 | WARNING | [ ] Comment refers to a TODO task "Test" (Generic.Commenting.Todo.TaskFound)
 2 | ERROR   | [ ] You must use "/**" style comments for a file comment (Squiz.Commenting.FileComment.WrongStyle)
------------------------------------------------------------------------------------------------------------

Time: 287ms; Memory: 6Mb
```

_Actual output:_
```
$ phpcs -s test.php

FILE: ...\test.php
------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 2 | ERROR | You must use "/**" style comments for a file comment (Squiz.Commenting.FileComment.WrongStyle)
------------------------------------------------------------------------------------------------------------

Time: 326ms; Memory: 6Mb

```

As you can see, phpcs is not reporting the Generic.Commenting.Todo sniff, even when I have re-included it after excluding the Generic sniff.

(I've ensured the config is being read properly - if I comment out the exclusion of Generic then I do in fact get the expected output. I've also tried re-including variations - Generic.Commenting and Generic.Commenting.Todo.TaskFound - and have also tried re-including inside the `<rule>`. Nothing I could think of trying could bring the Generic.Commenting sniff back, short of removal of exclusion of all of Generic).

Any ideas?

**Comment by gsherwood** [comment]
The docs have obviously provided confusion here. The annotated sample file is not an example file that would work as is - it's just showing all the various syntax you can use to perform actions.

You've never been able to exclude an entire standard and then selectively re-include sniffs from that standard. The exclude rule has always overwritten the include rule.

The reason for this is because you could have included a standard that explicitly includes the TODO sniff. Then you decide to exclude the entire Generic standard. PHPCS ends up in the same state (Generic is excluded but the sniff is included) even though the order was different. So it prefers the exclude rule over the include rule.

To be able to support what you are after, PHPCS would need to record the order of the exclude/include rules and use that to determine if an error code should be ignored or not, or if a sniff should be included or not. I haven't looked into how hard that would be, but it's probably a fairly big change.

To get what you want here, you're best bet would be to explicitly include the sniffs you want and not rely on the Squiz standard shortcut. That Squiz standard changes over time, so what it refers to will also change over time and that wont be immediately visible to you.

But if you really want to closely follow the Squiz standard, you could instead explicitly exclude just the Generic sniffs you don't want.

**Comment by tdmalone** [comment]
Ah. That makes sense. I misunderstood the purpose of the annotated-ruleset (or rather, I missed the warning at the top 'The file is designed for documentation purposes only' which I've just noticed ;) ).

Thanks for the quick reply and for explaining it. Of course supporting order of the rules would be fantastic but I understand that'd be a pretty significant (and breaking) change.

I'll rethink my approach.

**Comment by gsherwood** [comment]
No problem. Thanks for getting back to me.
