### ISSUE TITLE
Find issue with return on finally statement.

### ISSUE THREAD

**Issue by gmponos** [squizlabs/PHP_CodeSniffer#1921]
Anyone knows any sniff that can detect the case below?

``` php
<?php

function myFunction()
{
    try {
        throw new Exception('test');
    } catch (Exception $e) {
        throw new InvalidArgumentException();
    } finally {
        return 'test';
    }
}
```

The `InvalidArgumentException` will never reach the caller of the `myFunction`.

**Comment by ht-bs** [comment]
@gmponos what would you expect the sniff to do? I assume a warning that the exception will be lost? Since all involved clauses can contain arbitrary code I dont see a way around a full static analysis to check if any of the code paths ends with a return in the finally block. Is there some definition what circumstances lead to a `DISCARD_EXCEPTION` opcode.
