### ISSUE TITLE
Squiz.Functions.MultiLineFunctionDeclaration: Trailing space

### ISSUE THREAD

**Issue by kenorb** [squizlabs/PHP_CodeSniffer#1970]
Repro steps on empty folder:

1. `composer require squizlabs/php_codesniffer`
2. `git clone https://github.com/National-Theatre/drupal-phpunit.git`
3. `(cd drupal-phpunit; git reset 6d430d2a8d921bd983ac688c36da69f52190e816 --hard)`
4. `phpcbf --standard=Squiz --sniffs=Squiz.Functions.MultiLineFunctionDeclaration drupal-phpunit/src`

Result:

```
$ (cd drupal-phpunit; git diff)
--- a/src/NT/Drupal/Testing/Context/NTDrupalContext.php
+++ b/src/NT/Drupal/Testing/Context/NTDrupalContext.php
@@ -58,12 +58,14 @@ class NTDrupalContext extends DrupalContext
       }
     }
     
-    protected function refreshVariables() {
+    protected function refreshVariables() 
+    {
       global $conf;
       cache_clear_all('variables', 'cache_bootstrap');
       $conf = variable_initialize();
     }
-    protected function checkPermissions(array $permissions, $reset = FALSE) {
+    protected function checkPermissions(array $permissions, $reset = FALSE) 
+    {
```

Issue: There is a trailing space added after the curly bracket is moved to the next line.

**Comment by gsherwood** [comment]
I think you'll find that the space after the closing parenthesis just isn't being removed because this sniff doesn't see that as it's job. Within the Squiz standard, it's the job of the `Squiz.WhiteSpace.SuperfluousWhitespace` sniff. Specifically, the `Squiz.WhiteSpace.SuperfluousWhitespace.EndLine` error code, which you can include in your ruleset to have end of line whitespace cleaned up for you.

But some sniffs do minor cleanup when they are making changes and are sure the cleanup would be expected. I think this sniff can make that assumption here so I don't see any reason not to clean up that space if it is now the last content on the line (i.e., not comments exist between the parenthesis and open brace).

**Comment by gsherwood** [comment]
Just a note that the sniff ultimately making this fix is the `Generic.Functions.OpeningFunctionBraceBsdAllman` sniff, so that's the one that needs changing.

**Comment by gsherwood** [comment]
That extra space is now being removed as long as there isn't a PHP annotation on the line.
