### ISSUE TITLE
Custom report paths don't work on case-sensitive filesystems

### ISSUE THREAD

**Issue by micheledurante** [squizlabs/PHP_CodeSniffer#1996]
Hi, I have noticed that the constructor method for `src/Reporter.php` capitalises strings supplied by the `--report=` command line argument.

This breaks on case-sensitive filesystems.

**Comment by gsherwood** [comment]
I couldn't find any good reason for that ucfirst, so it probably came from old code to make things look nicer. I've removed it now. Thanks for letting me know.

**Comment by gsherwood** [comment]
Maybe those travis failures tell me why. Can't replicate locally so need to go digging again.

**Comment by gsherwood** [comment]
Forgot about autoloading. Needed that ucfirst just for the internal classes.

**Comment by jrfnl** [comment]
@gsherwood Just out of curiousity: why isn't the autoloader set up to be case-insensitive ? In PHP itself, classnames, namespace names (and keywords and function names) are treated case-insensitively.

**Comment by gsherwood** [comment]
> Just out of curiousity: why isn't the autoloader set up to be case-insensitive ?

It wasn't the autoloader itself, it's the fact that the file system on the test systems is case-sensitive. I didn't catch the error because the file system on my Mac is case insensitive. So it was really just that it was looking for the file `Reports/file.php` or `Reports/summary.php` instead of `Reports/Full.php` and `Reports/Summary.php` and just not finding it on the test systems.

**Comment by jrfnl** [comment]
:+1: Ah, snap.
