### ISSUE TITLE
Are we suppose to write "stateless" sniffs? 

### ISSUE THREAD

**Issue by enrmarc** [squizlabs/PHP_CodeSniffer#2019]
Context: I wrote a custom sniff which relies on state stored in class member variables.
Problem: When running my custom sniff on multiple files (for instance, as part of a pre-commit hook), it doesn't work properly.
What I think it's happening: it seems that my sniff is instantiated only once for all the files being analyzed. So, all class member variables keep their values even if the file being analyzed is a different one.

Is this intended? Are we suppose to write "stateless" sniffs?

**Comment by jrfnl** [comment]
I can't say anything about the background of this, but yes, that's the way sniffs work. They only get instantiated once.

As long as you don't use multi-threading/the `parallel` option, I suppose you could store the file name of the current file being examined in a class property, check the value at the start of the `process()` method and if different, reset the properties in which you keep track of the state.
If you do use the `parallel` option, you may still get it working, but in that case you'd probably need to store the state in a multi-level array with the file name as an identifier, though I have to admit I haven't looked deeply enough into how the `parallel` implemented to know for sure whether or not that would work.

Does that help ?

**Comment by gsherwood** [comment]
Instantiating a new sniff object for each sniff and every file was too expensive, so there is only one instance of the sniff for the entire run. There used to be some included sniffs that stored state information, but I don't think any of them do any more. I try to write sniffs that don't need to, just because it tends to be easier.

If a new needed to store state and clear it after each new file, I would give the sniff a private member var called `$currentFile` and store the value of `$phpcsFile->path` in there. Each time `process()` is called, I'd compare the value of $this->currentFile` and `$phpcsFile->path` and reset the member vars if they were different.

There might be a different way of writing your sniff where you don't need to do this, so if you'd like to share more information about it then I can have a think.

Often I just listen for T_OPEN_TAG, process the entire file myself, then have `process()` return `($phpcsFile->numTokens + 1)` so that my sniff doesn't get called for any additional open tags in the file. I'm not sure if that helps here, but it's a common pattern I use.

**Comment by enrmarc** [comment]
Thanks for the answers. Yes, what I did at the end was something like this (within the `process` method):

```
		if ($this->filename !== $phpcsFile->getFilename()) {
			$this->resetState($phpcsFile);
		}
```

Works fine. I was just wondering if there was another way to do it.

**Comment by gsherwood** [comment]
Glad it is all working. Thanks for posting your solution.
