### ISSUE TITLE
PSR2.Methods.MethodDeclarationSniff is too strict with underscore prefixes

### ISSUE THREAD

**Issue by fabacino** [squizlabs/PHP_CodeSniffer#2068]
Quoting the PSR-2 standard (from https://www.php-fig.org/psr/psr-2/, heading 4.2. Properties)

> Property names SHOULD NOT be prefixed with a single underscore to indicate
> protected or private visibility.

The sniff currently issues a warning whenever a method starts with a single underscore. However, if the method is `public`, the underscore obviously does not indicate `protected` or `private` visibility. Therefore there is no violation of the PSR-2 standard and the sniff should imho not warn about it in this case.

I can PR in case you agree.

**Comment by gsherwood** [comment]
I've searched the PHP-FIG mailing list for this issue and while I can find some references to underscore prefixes, the messages only talk about the issue in general terms and don't make a definitive ruling about public methods.

Based on those emails and my experience working with PEAR, my assumption is that rule means "don't prefix function calls with underscores because developers have used that to indicate visibility in the past" and was a direct attempt to discourage underscores at the start of functions, which is what the PEAR standard enforces. Before method visibility, public functions would never have been prefixed with an underscore, but private/protected would have. So this rule is there to say "where you were using underscores, don't use them any more". Given public functions were never prefixed with underscores, I assume they just didn't think to include that.

I've had that rule in the PHPCS PSR-2 standard for years so I wouldn't make a significant change like that unless the PHP-FIG clarified that underscores are allowed for public functions. It's hard to get a clear response as people have moved on, but feel free to try if you feel strongly about it. If I've made a mistake, I'll happily correct it.

**Comment by fabacino** [comment]
Thanks for your feedback. I didn't find anything either on the PHP-FIG mailing list and as you said, people have moved on. Personally, I think if they wanted to discourage all usage of a leading underscore in method names, they would have worded that paragraph differently (btw. I quoted the wrong one, should have been 4.3 Methods).

But I understand your point of view and since this is not really a problem for me, I will close the issue. It came to my attention, because I am working with codeception and there the leading underscore is used for special methods (discussed [here](https://github.com/Codeception/Codeception/issues/3071)).
