### ISSUE TITLE
Wiki: annotated ruleset page is now inaccessible

### ISSUE THREAD

**Issue by jrfnl** [squizlabs/PHP_CodeSniffer#2125]
Looks like the page name was changes to include `.xml` at the end causing browsers to try and interpret the page as xml ... and logically failing....

![phpcswiki](https://user-images.githubusercontent.com/663378/44196719-02643a00-a13d-11e8-8dad-aa91bc00e1ce.png)

**Comment by gsherwood** [comment]
Strange as I have not renamed that page since it was first created, and it still displays fine for me. Presumably because the content-type is being set correctly as text/html.

But it's not an XML file, so I'll rename to make sure that doesn't happen for browsers that ignore the content type and use the extension instead.

**Comment by gsherwood** [comment]
Done now: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset

**Comment by jrfnl** [comment]
It may be a change in how GH sends a `content-type` header to browsers ? Anyway, thanks for changing the title, that should prevent the issue altogether.

**Comment by gsherwood** [comment]
@jrfnl Thanks. Found 1 more as well.
