### ISSUE TITLE
Wrong suggestion for increment/decrement sniff

### ISSUE THREAD

**Issue by NicolasCARPi** [squizlabs/PHP_CodeSniffer#2354]
Hello,

First, thanks for this great tool :)

I believe I spotted an issue.

If you have:

~~~php
$a = 3;
echo $a += 1; // 4
~~~

You'll get an error (Squiz.Operators.IncrementDecrementUsage.Found), and the suggestion is to use `$a++`. But this is wrong in some cases, the correct suggestion imho would be to have `++$a`.

See: https://3v4l.org/KFHi9

What do you think?

Regards,
~Nico

Note: link to the code:
https://github.com/squizlabs/PHP_CodeSniffer/blob/957a2b63c084cc8b34cdb1a2c77ae12257c79a3d/src/Standards/Squiz/Sniffs/Operators/IncrementDecrementUsageSniff.php#L208

**Comment by jrfnl** [comment]
@NicolasCARPi Well, technically, the suggestion is not wrong.

When stand-alone, both `++$i` as well as `$i++` are equivalent to `$i += 1;` or `$i = $i + 1;`.

Problems can arise when `$i++` is used in a non stand-alone situation, like a function call, calculation or in an `echo` statement like in your 3v4l example etc, but the error you are referring to, will not be triggered in those cases.

All the same, I do agree that suggesting pre-in/decrement `++$i` rather than post-in/decrement `$i++` would encourage better coding practices, so maybe this could be changed into a feature request ? (as it's not a bug).

**Comment by NicolasCARPi** [comment]
You are right, indeed! :)

**Comment by jrfnl** [comment]
PR #2401 addressed this issue.

**Comment by NicolasCARPi** [comment]
Great :+1:
