### ISSUE TITLE
Indent errors for control structure

### ISSUE THREAD

**Issue by KeironLowe92** [squizlabs/PHP_CodeSniffer#2356]
I seem to be getting errors about the indentation when using control structures, this is what I think it should be...

![screenshot 2019-01-10 at 09 11 33](https://user-images.githubusercontent.com/4272731/50958258-322f2800-14b8-11e9-918a-b69efbddec09.png)

But it wants me to format it to this...

![screenshot 2019-01-10 at 09 11 47](https://user-images.githubusercontent.com/4272731/50958273-3ce9bd00-14b8-11e9-9749-eea63ede67e0.png)

I'm using the PSR2 standard.

**Comment by gsherwood** [comment]
That's because you've indented your code 4 spaces from the opening tag. That standard assumes you've started all code at the same level as the opening tag (as you would for normal class file) even if you happen to be using it inside a template file.

The sniff normally allows code to be indented "at least 4 spaces" (but can be more) but it always requires control structures to be indented correctly, which is why it wants no space there.
