### ISSUE TITLE
array indent exact error 

### ISSUE THREAD

**Issue by chipco** [squizlabs/PHP_CodeSniffer#2386]
Generic.WhiteSpace.ScopeIndent.IncorrectExact generates false errors for array assignment.

![image](https://user-images.githubusercontent.com/2259671/51770284-046bf500-20ee-11e9-8026-406458fb35b6.png)

**Comment by valeryan** [comment]
I am having the same issue. I thought I might add the token to the ignored list but I am not sure that's the best way to go.

**Comment by valeryan** [comment]
Also when using tabs and this error occurs the fixer will replace the tabs with spaces and not respect the tabIndent value...

**Comment by gsherwood** [comment]
@chipco I can't replicate any errors with the code in your screenshot. Are you able to post a snippet of code (text please, not a screenshot) that replicates the error with the built-in standards?

@valeryan If the fixer is replacing tabs with spaces, it may be because the standard you are using does not include the `Generic.WhiteSpace.DisallowSpaceIndent` sniff.

**Comment by valeryan** [comment]
It does include that I have issues with this sniff with almost anything that is in short arrays. I have just been disabling everything that is having this issue. I just found something I am missing. It is only replacing things in short arrays with spaces and only if I have exact set to true. You can see my setup here. https://github.com/HydraWiki/hydrawiki-codesniffer. If you would like I can set up a branch with the scoped indent sniff without the ignore block so you can see the full problem.

**Comment by valeryan** [comment]
The issue I am having is this problem and conflict with `Generic.Arrays.ArrayIndent` rule. I want to use scoped indent for most things when it works but it for some reason does not like indenting arrays. I have not tested without tabs though. I created a repo that just has this issue highlighted here: https://github.com/valeryan/scopedindent.

**Comment by valeryan** [comment]
I think this issue and issue #2372 are related. I updated https://github.com/valeryan/scopedindent to show both errors occurring with this rule.

**Comment by gsherwood** [comment]
Thanks for the sample code. The issue with exact checking inside short arrays has been fixed in 3.4.1: https://github.com/squizlabs/PHP_CodeSniffer/commit/390bffe2265aac8184fdf86400c0d0841e65bc4b

I'm going to close this issue as the chained method calls one is quite different from a code point of you.
