### ISSUE TITLE
PSR12: space between closing parentheses and type declaration

### ISSUE THREAD

**Issue by hacktivista** [squizlabs/PHP_CodeSniffer#2397]
Given the following code example:
```
public function functionName(int $arg1, $arg2) : string
{
    return 'foo';
}
```

An error should be thrown, given that PSR12 states

> When you have a return type declaration present there MUST be one space after the colon followed by the type declaration. The colon and declaration MUST be on the same line as the argument list closing parentheses **with no spaces between the two characters**.

**Comment by gsherwood** [comment]
PSR-12 support is still in progress. It's actually been on hold for a while until the PSR goes back into review, which it should very soon.

This specific line in the PSR has not been implemented yet.

I'm going to close this issue because there is already an in progress issue for PSR-12: https://github.com/squizlabs/PHP_CodeSniffer/issues/750
