### ISSUE TITLE
Exclude pattern for specific rule is excluding the whole sniff

### ISSUE THREAD

**Issue by benignant** [squizlabs/PHP_CodeSniffer#2440]
I have the following ruleset:

```xml
<?xml version="1.0"?>

<ruleset>
    <rule ref="PSR1.Classes.ClassDeclaration.MissingNamespace">
        <exclude-pattern>*/database/*</exclude-pattern>
    </rule>

    <rule ref="PSR2"/>
</ruleset>
```

And the following code in a file that matches the above exclude pattern:

```php
<?php

class Test1
{
}

class Test2
{
}

```

However PHP_CodeSniffer is not outputting an error for the `PSR1.Classes.ClassDeclaration.MultipleClasses` rule that is being violated in the above code. This implies that PHP_CodeSniffer is excluding more than just `MissingNamespace`.

I have confirmed that other PSR1 rules _are_ being applied, so it seems to be excluding all of `PSR1.Classes` or `PSR1.Classes.ClassDeclaration`.

Here's a quote from the [wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset) that demonstrates this feature:

> ```xml
> 
> <rule ref="Squiz.Strings.DoubleQuoteUsage.ContainsVar">
>    <exclude-pattern>*/tests/*</exclude-pattern>
>    <exclude-pattern>*/data/*</exclude-pattern>
> </rule>
> ```

**Comment by jrfnl** [comment]
Hi @benignant, this is due to the order of the rules in your ruleset.

You first include the `PSR1.Classes.ClassDeclaration.MissingNamespace` error code as an individual errorcode. This leads to everything else in the PSR1 ruleset being ignored.

Only after that, you include `PSR2`, which includes `PSR1`, but won't reset the ignores created by the earlier directive.

If you change the order around, like below, `PSR2` will be included first and will include the whole of `PSR1`.

Now when the `PSR1.Classes.ClassDeclaration.MissingNamespace` rule is included afterwards, it will only affect that errorcode and won't touch the other `PSR1` errorcodes which are already included.

```xml
<?xml version="1.0"?>
<ruleset>
    <rule ref="PSR2"/>

    <rule ref="PSR1.Classes.ClassDeclaration.MissingNamespace">
        <exclude-pattern>*/database/*</exclude-pattern>
    </rule>

</ruleset>
```

Hope this helps.
