### ISSUE TITLE
Release 3.4.1 because 3.4.0 breaks Drupal Coder's PHPUnit tests

### ISSUE THREAD

**Issue by klausi** [squizlabs/PHP_CodeSniffer#2444]
The master branch of PHP_CodeSniffer has fixes that are required to make Coder's tests pass again. Which means Coder has to depend on a PHPCS composer git clone which is a 200MB large, problematic for users with low bandwidth. See https://github.com/pfrenssen/coder/pull/22

Can you release 3.4.1 to mitigate that?

Thanks!

**Comment by jrfnl** [comment]
@klausi What is the particular fix included in `master` you are referring to ?

**Comment by klausi** [comment]
Something in the Zend standard that handles closing PHP tags. Did not run a git bisect to find out the exact commit.

**Comment by jrfnl** [comment]
@klausi Ok, thanks for responding.

Just wondering - do most of your users use Composer to install `Coder` ? If so, setting the `conflict` property might help (that is, if I understand you correctly and there wasn't a problem pre-3.4.0).
Ref: https://getcomposer.org/doc/04-schema.md#conflict

---

This relates to #2146 which was fixed by e64a980f7bc5a68a4d720e3e74f68d3997bf919e in 3.4.0, however that commit introduced another issue which in turn was fixed by PR #2280 / commit 96029ccf71a3e5160817760850e8bbfbe6f09b5c which will be included in 3.4.1.

**Comment by klausi** [comment]
Thanks, the conflict property might be a good option if we would be in a hurry to release a new Coder version, but we are not. It is just a matter of our automated tests being broken while we develop. So the annoying large download only affects developers that want to run Coder's dev version.

The closing tag bug only happens on fringe cases that will not affect many Coder users.

So the new PHPCS release is not urgent, just something that would make our lives in Coder development easier :-)

**Comment by gsherwood** [comment]
I will release 3.4.1 - I just haven't had a spare moment to get back to PHPCS work for a couple of weeks as my paying job has been crazy.

Going to close this.
