### ISSUE TITLE
Check number of function arguments

### ISSUE THREAD

**Issue by Gobd** [squizlabs/PHP_CodeSniffer#2466]
Is it possible to check if the number of function arguments is correct? If I have this function `add($key, $data, $expire = 0)` is there a sniff to ensure it is called with two (or event three would be fine) arguments?

**Comment by gsherwood** [comment]
No, there is no sniff to do this. You'd have to write a custom sniff to enforce custom rules like this, or a new generic sniff needs to be written that can be configured with an array of function names mapping to the number of required arguments.

If you're looking for a generic sniff just to ensure that functions are being called with the minimum number of required arguments to stop fatal errors during runtime, PHPCS is probably the wrong tool for the job. While PHPCS can look over an entire project at once, it's more commonly used to check a single file. When doing so, PHPCS has no project context, so it has doesn't know the function signatures of all the functions being called.

On top of this, I think you'll find a static analysis tool incapable of catching all incorrect calls to functions due to the fact that functions can be called dynamically. As the function name, and even argument list, is only available at runtime, you'll need to rely on unit tests to catch these sort of problems.

**Comment by adamzero1** [comment]
Here is an example we use, we are checking if the second argument passed to `print_r` is `true`, which isn't exactly what you are asking for, but should give you a good starting point to start querying argument counts and values passed to functions.
[Disallow print_r direct output](https://gist.github.com/adamzero1/835bf6a5dfcd1c68156edd04ea5a241a)
