### ISSUE TITLE
v3.3.0 introduces BC break by removing Squiz.PHP.ForbiddenFunctions

### ISSUE THREAD

**Issue by slepic** [squizlabs/PHP_CodeSniffer#2531]
up to v3.2.3 that sniff works fine
in 3.3.0 the sniff is removed, but you cannot just remove a feature without breaking compatibility.
I know it is replaced by Generic.PHP.ForbiddenFunctions with setting, but thats not enough.
If one uses the whole ruleset of Squiz, it is ok.
But if we have project where we have our own ruleset with only few Squiz rules picked out by references, then it breaks when we reference Squiz.PHP.ForbiddenFunctions.
You should mark the sniff deprecated, make the Squiz ruleset not use it, but remove no sooner then 4.0.0.
Well I have already replaced it in our ruleset, So I am fine, so I merely want to point out that this approach was not entirely correct, and politely ask you to think about it next time you're going to remove a sniff or take any similar action...

**Comment by gsherwood** [comment]
Thanks for the feedback. This is something that has been addressed since 3.3.0 (now 12 months old) by adding some rules to the versioning numbering into the project README: https://github.com/squizlabs/PHP_CodeSniffer#versioning

As per those new rules, the sniff would not have been removed - it would have been deprecated for removal in 4.0, as you suggested.

Do you think those rules address your concerns?

**Comment by slepic** [comment]
Well, this happened to me when I was upgrading from 2.9.1 to latest.
As for the versioning rules, I dont think there is a rule that fits this situation.
It might be covered in the rule for MAJOR increment:
```backwards-incompatible changes are made to the API used by sniff developers```
But it is actualy used rather by a sniff consumer then a developer. And it could use something more explicit like in the MINOR increment rule:
```new sniffs are added to an included standard```
something like:
```existing sniffs included in a standard are removed or modified in backward incompatible manner``` for the MAJOR increment...

**Comment by gsherwood** [comment]
> Well, this happened to me when I was upgrading from 2.9.1 to latest.

Yes, that's because the change was made in 3.3.0 and you went through that version to get the the latest. 3.3.0 was already released before the versioning changes were made, which is why it doesn't adhere to them.

> As for the versioning rules, I dont think there is a rule that fits this situation.

I meant it to be `backwards-compatible changes are made to the ruleset.xml format`, but you are right that it is not clear there. The idea is that for a minor version, your ruleset should continue to function without you changing it. It might not report the exact same errors, but it will still be valid.

It's late where I am now, but I'll make some modifications to the wording tomorrow.

**Comment by gsherwood** [comment]
Sorry, I got very busy so it took me a lot longer to review the text. I've made some changes to the readme now that hopefully clarify this:
- MINOR versions are used for when an existing sniff is removed from an included standard, but the sniff code still works
- MAJOR versions are used for when sniffs are removed from PHPCS

Do you think those changes explain things?

**Comment by slepic** [comment]
Well, I'm not sure if get ir right. But it seems to me that what you described in the minor applies to what happened to me and this was a BC break, so it should be in major...

**Comment by gsherwood** [comment]
What happened to you was that a sniff was removed from PHPCS entirely. So as per the versioning information, that should only happen in a major version release.

**Comment by slepic** [comment]
Ah, you are  right, sry for confusion..

**Comment by gsherwood** [comment]
No problem. Thanks for reviewing the changes. I'll close this issue now that the versioning information has been adjusted.
