### ISSUE TITLE
why cant one argument is allowed per line in a multi-line function call

### ISSUE THREAD

**Issue by nick2550123097** [squizlabs/PHP_CodeSniffer#2569]
right:
  
   $this->fireCallbackArray(
            $object,
            $this->getCallbacksForType($abstract, $object, $this->resolvingCallbacks)
        );

error:
     $this->fireCallbackArray(
            $object, $this->getCallbacksForType($abstract, $object, $this->resolvingCallbacks)
        );

**Comment by gsherwood** [comment]
I'm not exactly sure what you are asking, so sorry if this doesn't answer your question.

The second code block is a multi-line call because it spans multiple lines, but you've put both arguments on the same line. The standard you are using obviously wants one per line.

So your first code block is fine because it puts one argument per line. Or you could write the code like this:
```php
$this->fireCallbackArray($object, $this->getCallbacksForType($abstract, $object, $this->resolvingCallbacks));
```
But the line gets very long this way.

**Comment by gsherwood** [comment]
Closing due to lack of feedback.
