### ISSUE TITLE
Incorrect indentation in array arguments

### ISSUE THREAD

**Issue by spaceemotion** [squizlabs/PHP_CodeSniffer#2631]
Given the following snippet, the PSR12 fixer reformats the following code:

```php
BlogCategory::query()->updateOrCreate([
                                          'id' => $id,
                                      ],
                                      [
                                          'value'       => $value,
                                          'text'        => $text,
                                          'recommended' => $recommended,
                                      ]);
```

like this:

```php
BlogCategory::query()->updateOrCreate(
    [
                                          'id' => $id,
                                      ],
    [
                                          'value'       => $value,
                                          'text'        => $text,
                                          'recommended' => $recommended,
    ]
);
```

And not as expected:

```php

BlogCategory::query()->updateOrCreate(
    [
        'id' => $id,
    ],
    [
        'value'       => $value,
        'text'        => $text,
        'recommended' => $recommended,
    ]
);
```

---

```
php phpcbf.phar --version
PHP_CodeSniffer version 3.5.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by gsherwood** [comment]
PSR-12 says nothing about array indents so none of the PSR-12 sniffs attempt to fix array indents even when code changes around them. All the PSR-12 fixers try to do is make enough changes to ensure the code now passes PSR-12.

Sniffs could try and understand that they are moving a short array opener to a new line and then try and maintain the relative indent of the internal lines, but this is more complex than it might appear due to the enormous number of edge cases.

Your sample code (assuming you are using 4-space indent) you've used precision indenting with whitespace to line up the closing array bracket with the opener. PSR-12 has no idea that this is a convention you want to enforce, and it can't guess as to how you'd then want the content to be indented. It could see that the first line in array is indented 4 spaces from the opener, but it's not resting at a tab stop, so you may be using precision indenting in there as well.

That's just one example of how someone might write their code. What if it was this, with no indent for the first item:
```php
BlogCategory::query()->updateOrCreate(['id' => $id,
    ],
    [
        'value'       => $value,
        'text'        => $text,
        'recommended' => $recommended,
    ]);
```
Or this, where the array lines are indented less than the opener itself:
```php
BlogCategory::query()->updateOrCreate([
    'id' => $id,
],
[
    'value'       => $value,
    'text'        => $text,
    'recommended' => $recommended,
]);
```
I could certainly hand-craft a solution for each so that it tries to maintain the spirit of the developer's coding standard in this exact case, but that's very difficult and time consuming. PHPCS wants you to include an array indent sniff instead, so that the rules are very clear to it.

There is an included array indent sniff that enforce a single 4-space indent of all multi-line arrays. You can try it out by creating a custom ruleset.xml file that looks like this:
```xml
<?xml version="1.0"?>
<ruleset name="MyStandard">
    <description>PSR-12 with array indenting</description>
    <rule ref="PSR12" />
    <rule ref="Generic.Arrays.ArrayIndent" />
</ruleset>
```
Then run PHPCS or PHPCBF with `--standard=/path/to/ruleset.xml`. On your sample code, PHPCBF fixes it like this:
```php
BlogCategory::query()->updateOrCreate(
    [
        'id' => $id,
    ],
    [
        'value'       => $value,
        'text'        => $text,
        'recommended' => $recommended,
    ]
);
```
Which looks to be what you are after, although I'm not sure if your array indenting rules are more specific than that.

Does that help explain things?

**Comment by spaceemotion** [comment]
Thanks for the detailed explanation, will try that out as soon as i can

**Comment by spaceemotion** [comment]
Okay, that indeed fixes quite a lot of things, but I got one "edge case" where it failed:

```php
BlogCategory::query()
    ->with(['posts.author' => function ($query) {
        $query->where('is_public', true);
    }])
    ->get();
```

becomes:

```php
BlogCategory::query()
    ->with(['posts.author' => function ($query) {
        $query->where('is_public', true);
    }
    ])
    ->get();
```

**Comment by gsherwood** [comment]
Try this ruleset:
```xml
<?xml version="1.0"?>
<ruleset name="MyStandard">
    <description>PSR-12 with array indening</description>
    <rule ref="PSR12" />
    <rule ref="Generic.Arrays.ArrayIndent">
        <exclude name="Generic.Arrays.ArrayIndent.CloseBraceNotNewLine"/>
    </rule>
</ruleset>
```

**Comment by spaceemotion** [comment]
Yep that was it thanks! So it seems like I mistook PSR-12 for also "dictating" how arrays are have to be indented. Good to know you can customize it like this. Cheers!

**Comment by gsherwood** [comment]
No problem. Glad it is working now.
