### ISSUE TITLE
Fatal Error using phpcs + phan due to MethodDeclarationUnitTest PSR2 test file

### ISSUE THREAD

**Issue by johnsaigle** [squizlabs/PHP_CodeSniffer#2655]
Fatal error: Cannot use the final modifier on an abstract class member in vendor/squizlabs/php_codesniffer/src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc on line 15

The above error is causing a project that I work on to fail on TravisCI:

[debug] Running '/home/travis/.phpenv/versions/7.2.15/bin/php' '-n' '-c' '/tmp/tPRhPF' 'vendor/bin/phan'
PHP Fatal error:  Cannot use the final modifier on an abstract class member in vendor/squizlabs/php_codesniffer/src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc on line 15

Curiously, our 7.3 build works, just not PHP 7.2.

Is this a known issue or do you have any suggestions?

Link to issue in job: https://travis-ci.org/aces/Loris/jobs/598926139#L3704

**Comment by jrfnl** [comment]
Why are you running code analysis over your dependencies ? And more specifically _on the unit tests_ of your dependencies ???

**Comment by johnsaigle** [comment]
@jrfnl I'm not; the `vendor/` directory for composer is excluded from `phan`'s analysis, so it's not analyzing the source code for PHPCS (or itself, or anything else) because you're right that doesn't make sense.

Still, it's somehow the combination of these tools that it causing my problem.

**Comment by gsherwood** [comment]
The unit test files contain a lot of invalid code. I could commit a change for this because I doubt the test actually cares about it being there, but you'd find more invalid code all over the place. I suggest looking into the phan config to see if you can figure out why it is checking these test files.

I'm closing this as there isn't anything I can change in PHPCS to stop these errors, short of removing all invalid code from the unit test files, which defeats the purpose of those files.
