### ISSUE TITLE
Which sniff can check a whitespace after comma in single line array/list.

### ISSUE THREAD

**Issue by Moln** [squizlabs/PHP_CodeSniffer#2687]
Help, I need check a whitespace after comma in single line array/list.

Code:

```php
[$a,$b,$c] = ['a','b','c'];

// convert to 

[$a, $b, $c] = ['a', 'b', 'c'];
```

Version: 3.5.1

------------------------

I saw the `Squiz.Arrays.ArrayDeclaration` source code, and config `Squiz.Arrays.ArrayDeclaration.SpaceAfterComma` rule, but it's does not work.

```
<rule ref="Squiz.Arrays.ArrayDeclaration.SpaceAfterComma" />
```

**Comment by gsherwood** [comment]
That error code is the one you are looking for, but the sniff itself is not designed to make it available for use. This is because the sniff throws a `SingleLineNotAllowed` error when it finds an array declared with multiple values - it wants the array to be defined using one value per line.

This is a result of bad sniff design, which has been documented here: #582

I'm going to close this issue and put your comment over onto that one. It's not something that is going to get done quickly (it's probably a version 4 thing) but at least it will make sure this specific case is considered.
