### ISSUE TITLE
Wrong if block intendation with JS array functions

### ISSUE THREAD

**Issue by laoneo** [squizlabs/PHP_CodeSniffer#2747]
Discovered a small bug when using arrow functions in Javascript. The fixer intends the **if** wrong when there are nested arrow functions. Here is a demo:

### Before the fix
```
const demo = () => {
    let someVar;
    [].forEach((item, index) => {
    });

    if (someVar == null) {
        someVar = 'foo';
    }
}
```

### After the fix
```
const demo = () => {
    let someVar;
    [].forEach((item, index) => {
    });

if (someVar == null) {
    someVar = 'foo';
}
}
```

The command I'm running is on version 3.5.3:
`vendor/bin/phpcbf --colors --standard=PSR2 test.js`

**Comment by gsherwood** [comment]
PHPCS does not support ES6 syntax. JS checking support will be removed from PHPCS in version 4, so I suggest looking into a different tool (such as eslint) and migrating away from PHPCS for JS coding standards as soon as possible.

I'm going to close this issue because I don't want to give developers the impression that this feature may be added to PHPCS in the future.

**Comment by laoneo** [comment]
It was just convenient to have the same checker for PHP and JS files. But makes sense to skip JS, as the JS world is driving in it's own direction.
