### ISSUE TITLE
Setting extensions not documented in Annotated Ruleset

### ISSUE THREAD

**Issue by ravage84** [squizlabs/PHP_CodeSniffer#2757]
I wanted to set the to be checked file extensions in my ruleset file.
But nothing like that is documented in the [Annotated Ruleset](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset).

Apparently, the following works:

```` xml
<arg name="extensions" value="php,ctp" />
````

So, I recommend that to be added to the Annotated Ruleset.

Additionally, it could be mentioned under [Advanced Usage](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#specifying-valid-file-extensions), too.

**Comment by gsherwood** [comment]
This is just because there are a lot of command line arguments, and you can set them all in this way (except for the few listed in the annotated ruleset). As new CLI arguments are added, they aren't all re-documented in the annotated ruleset - it would get too long.

But point taken. This one is also probably a common one, so it would make sense to also include it in the example.

**Comment by gsherwood** [comment]
I've made that change now.
