### ISSUE TITLE
Add Phpunit 8 support in require-dev

### ISSUE THREAD

**Issue by VincentLanglet** [squizlabs/PHP_CodeSniffer#2781]
The tests are actually not compatible with phpunit8.
Adding some support would be great.

**Comment by GlennM** [comment]
And PHPUnit 9 perhaps :)

**Comment by jrfnl** [comment]
The tests will run fine on PHP 8 using PHPUnit 7, see the builds on Travis.

Adding support for PHPUnit 8/9 in PHPCS 3.x is not an option due to the `void` return type which requires PHP 7.1, while PHPCS still supports PHP 5.4.

PHPCS 4.x will have a minimum PHP requirement of PHP 7.2 and already supports PHPUnit 8 and 9.

**Comment by gsherwood** [comment]
Closing this as support has been added to version 4

**Comment by GlennM** [comment]
> Closing this as support has been added to version 4

Thanks. Any idea when version 4 will be ready? I see a lot has been implemented, 4 items are selected for dev and 4 items on backlog.

**Comment by gsherwood** [comment]
> Any idea when version 4 will be ready?

No, I don't have a date. Once PHPCS has full PHP8 support, I'll be able to get back to it. There aren't a lot of items left, but some of them are pretty big.
