### ISSUE TITLE
ES6 const array issue

### ISSUE THREAD

**Issue by alecpl** [squizlabs/PHP_CodeSniffer#2785]
Following javascript code
```
const routes = [
    {
        path: '/',
        redirect: { name: 'login' }
    },
    {
        path: '/dashboard',
        name: 'dashboard',
        component: DashboardComponent,
    }
]

const router = new VueRouter({
        mode: 'history',
        routes
})
```
is considered invalid in a few places. phpdbf converts it to
```
const routes = [
    {
        path: '/',
        redirect: { name: 'login' }
    },
    {
        path: '/dashboard',
        name: 'dashboard',
        component: DashboardComponent,
    }
    ]

    const router = new VueRouter({
        mode: 'history',
        routes
    })
```
Which is imo wrong.

Used phpcs 3.5.3. PHP 7.4. Rules: PSR1 + PSR12

**Comment by gsherwood** [comment]
PHP_CodeSniffer does not support modern JS syntax. All JS functionality will be removed in version 4 and no bugs will be fixed in version 3. I strongly suggest switching to a dedicated JS linting tool like eslint.

The version 4 roadmap can be found here: https://github.com/squizlabs/PHP_CodeSniffer/milestone/11

The specific issue for this is here: https://github.com/squizlabs/PHP_CodeSniffer/issues/2448
