### ISSUE TITLE
Question/Feature request: disable PHPCBF check in PHPCS

### ISSUE THREAD

**Issue by LukeWCS** [squizlabs/PHP_CodeSniffer#2829]
I don't want/need the PHPCBF hint and "[x]" in reports. Is there a way to disable this?

Currently I have two options to solve this: 
1) Removing all PHPCBF parts with RegEx from the report.
2) Disable one line in one file of PHPCS.

Both works, but a regular option like a new CLI parameter would be the much better way.

**Comment by gsherwood** [comment]
There is currently no way to disable this.

**Comment by jrfnl** [comment]
@LukeWCS Since PHPCS 3.3.0, it has become easier to work with custom reports. As there have been no other requests for this feature, I suggest a custom report may be the way to go (i.e. basically a customized version of the `Full` report).

Does that sound like a workable solution for you ?

@gsherwood We may want to consider adding a section about using custom reports to the [Wiki Reporting](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Reporting) page. What do you think ?

Refs related to custom reports:
* https://github.com/squizlabs/PHP_CodeSniffer/issues/1942
* https://github.com/squizlabs/PHP_CodeSniffer/pull/1948

**Comment by LukeWCS** [comment]
@jrfnl 

I have my own function in my analysis system that I use to completely process the PHPCS logs. For example, the log is converted to HTML and prepared in such a way that each file has its own section that can be expanded.

https://www.wcsaga.org/public/extcheck/en_ec_demo_failed.html

This function does other processing, including the removal of PHPCBF hints. PHPCBF is generally not relevant for us. This has worked flawlessly for years and I guess it would be more of an additional effort for me to create individual reports with PHPCS.

**Comment by jrfnl** [comment]
@LukeWCS Not sure what you mean by "create individual reports with PHPCS", a report is basically a sort of template format to present the results of a PHPCS run, so I imagine some of the processing you are doing in your script would not be necessary if you'd be using a custom report which only returned the information you want to use/need.

Having said that and looking at your report, you are combining the results of multiple PHPCS runs, so you'd still need your own script anyway.

As you say that your current setup is working fine for your needs, can this issue be closed ?

**Comment by LukeWCS** [comment]
Yes, can be closed. Thanks anyways.
