### ISSUE TITLE
how to show PHP Notice exceptions (Undefined index)

### ISSUE THREAD

**Issue by zanona** [squizlabs/PHP_CodeSniffer#2890]
Hi,
Apologies if I'm missing something from the docs or in case this isn't the correct place for posting questions.

Is there any way of setting phpcs in a way it displays PHP Notice exceptions? I believe some of them are only caught at runtime and it would be impossible to guess what would happen.

But in case I have something like the below identified, it would be really great.

```php
$foo = array();
echo $foo['bar']; // <-- PHP Notice: Undefined index: foo in file.php on line 2
```

Any help would be appreciated as I am still getting the hang of PHP.
Thanks in advance.

**Additional info**

```sh
$ phpcs --version
PHP_CodeSniffer version 3.5.4 (stable) by Squiz (http://www.squiz.net)
```

<details>
  <summary><b>.phpcs.xml</b></summary>

```xml
<?xml version="1.0"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" name="PHP_CodeSniffer" xsi:noNamespaceSchemaLocation="phpcs.xsd">

    <description>The coding standard for PHP_CodeSniffer itself.</description>

    <file>theme/</file>
    <exclude-pattern>theme/*\.(less)$</exclude-pattern>

    <rule ref="WordPress">
        <exclude name="Squiz.Commenting.InlineComment.InvalidEndChar"/>
        <exclude name="Squiz.Commenting.FileComment.Missing"/>
        <exclude name="Squiz.Commenting.FunctionComment.Missing"/>
        <exclude name="Squiz.Commenting.FunctionComment.WrongStyle"/>
        <exclude name="Squiz.PHP.CommentedOutCode.Found"/>
        <exclude name="Generic.Formatting.MultipleStatementAlignment.NotSameWarning"/>
        <exclude name="WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned"/>
        <exclude name="WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound"/>
    </rule>

    <rule ref="VariableAnalysis"/>

    <rule ref="ImportDetection"/>
    <rule ref="ImportDetection.Imports.RequireImports">
        <properties>
            <property name="ignoreWordPressSymbols" value="true"/>
            <property name="ignoreUnimportedSymbols" value="/^(register_block_type|get_the_ID)$/"/>
        </properties>
    </rule>

    <rule ref="PSR2.Classes.PropertyDeclaration.Underscore">
        <type>error</type>
    </rule>

</ruleset>
```
</details>

**Comment by jrfnl** [comment]
Well, you could look into adding the external `VariableAnalysis` ruleset: https://github.com/sirbrillig/phpcs-variable-analysis/ , though I'm not 100% sure array indexes are covered yet. /cc @sirbrillig

**Comment by sirbrillig** [comment]
Yeah, VariableAnalysis doesn't check array indices or object properties; both of those are tricky for a linter because they are much more frequently dynamic and they are much more frequently assigned outside the current file. Even static analysis tools (eg: [phpstan](https://github.com/phpstan/phpstan), [psalm](https://psalm.dev/)) probably have trouble with "undefined index" errors, but I'd suggest trying those tools out if this is the kind of safety you're looking for. 

It's not an answer to your question but if you control the data in question it might be a good opportunity to use value objects rather than associative arrays. That would also make it much easier for a static analysis tool to know if a property exists.

```php
class Foo {
  public $baz;
}
$foo = new Foo();
echo $foo->bar; // <-- PHP Undefined property Notice, but one that a static analyser could easily detect
```

**Comment by zanona** [comment]
Thanks so much for the insights, folks.

I'm having a look right now on using value objects and Psalm.
