### ISSUE TITLE
Redundant curly brace interpreted as case start

### ISSUE THREAD

**Issue by ameenross** [squizlabs/PHP_CodeSniffer#3016]
Since I don't like to manually indent switch/cases, I've recently started using statement groups.

```php
switch ($foo) {
    case 1: {
        echo 'code';
    }
    case 2:
    {
        echo 'code';
    }
}
```

Unfortunately this yields the following error:

> CASE statements must be defined using a colon (PSR2.ControlStructures.SwitchDeclaration.WrongOpenercase)

It doesn't matter if the curly brace is on the same line or the next.

**Comment by ameenross** [comment]
Using this workaround for now:

```php
switch ($foo) {
    case 1: { // phpcs:ignore PSR2.ControlStructures.SwitchDeclaration.WrongOpenercase
        echo 'code';
    }
}
```

**Comment by gsherwood** [comment]
When you use braces like this, PHPCS uses the closing brace to as the end of the CASE or DEFAULT statement. So that everything matches up, the matching opening brace is used as the opener. This only happens in the statement group is surrounding the entire CASE or DEFAULT body, as you are doing here.

If PHPCS doesn't do this, it causes all sort of issues with indentation and scope end detection, so it's not something I'm going to muck around with.

The error itself is (debatably) correct as your SWITCH declaration is not formatted the way PSR2 expects.

If you want to keep using PSR2 with your way of defining SWITCH statements, it might be worth using a custom ruleset to completely ignore this part of PSR2:
```xml
<?xml version="1.0"?>
<ruleset name="My Standard">
    <description>Custom PSR2</description>
    <rule ref="PSR2">
        <exclude name="PSR2.ControlStructures.SwitchDeclaration.WrongOpenercase"/>
    </rule>
</ruleset>
```
Store that in your project root in a file called `.phpcs.xml` and then just run PHPCS without a `--standard` argument and you'll get PSR2 without that error message.

Does that help?

**Comment by ameenross** [comment]
Thanks. That works of course.

**Comment by ameenross** [comment]
Sorry, I got the impression that this is a wontfix so I closed it. But reopening since you added it to a project.

**Comment by gsherwood** [comment]
Sorry for the confusion. I add to the project to help me track the issue better, but the workflow marks it as released when closed. I've remove it from the project and will close it now.
