### ISSUE TITLE
Is it a good idea to make sniffs for PSR naming conventions as in php-fig?

### ISSUE THREAD

**Issue by annechko** [squizlabs/PHP_CodeSniffer#3054]
There is a PSR Naming Conventions https://www.php-fig.org/bylaws/psr-naming-conventions/

**1. Interfaces MUST be suffixed by Interface: e.g. Psr\Foo\BarInterface.
2. Abstract classes MUST be prefixed by Abstract: e.g. Psr\Foo\AbstractBar.
3. Traits MUST be suffixed by Trait: e.g. Psr\Foo\BarTrait.**

And I made sniffs to check these cases (need it for my project)

Is it a good idea to create a pull request with them here? To create new standard PHPFIG for example?
Or is it too specific for this project and not really necessary in here?

**Comment by gsherwood** [comment]
I think that having a standard that applies to PHP-FIG PSR-specific naming is too specific, but the general idea of having sniffs to enforce that naming convention is a really good one.

If you'd be happy to contribute the sniffs, I would accept them into the Generic coding standard so that developers can choose to add them to their custom standards.
