### ISSUE TITLE
Command "phpcs ." doesnt work correctly

### ISSUE THREAD

**Issue by Solvent13** [squizlabs/PHP_CodeSniffer#3392]
I want to check all folders, files in the current directory and, accordingly, i enter the command "**phpcs .**" where the comma - is the current directory path. But CodeSniffer for some reason lists all 18989 errors with their description before displaying the "real" report. However if i set specific path (e.g. "phpcs file.php") then CodeSniffer works correctly.

**Comment by jrfnl** [comment]
@Solvent13 I'm not 100% sure what you are saying here. In this (rare) case, I think a screenshot may help to clarify the question.

Your description vaguely brings an issue to mind where PHPCS didn't ever really finish because it ran out of memory. Based on what you describe, you may want to try to raise the `memory_limit` in your `php.ini` file and see if that makes a difference.

Other than that and if this really would be a bug in PHPCS, more information is needed, like the OS you are running on, the PHPCS version, the PHP version, potentially information about the size of the project and the ruleset used etc.
All of these are requested in the bug report template, however, none of them are listed in your issue, so there is not much anyone can do based on the information currently available.

**Comment by Solvent13** [comment]
ok, I have made a bug report
