### ISSUE TITLE
PSR-12 and alternative syntax of control structures

### ISSUE THREAD

**Issue by WinterSilence** [squizlabs/PHP_CodeSniffer#3461]
**Describe the bug**
PSR-12 not define coding style for alternative syntax of control structures.

**Code sample**
```php
<?php foreach ($fields as $field): ?>
   <?= $field['value'] ?>
<?php endforeach ?>
```

**To reproduce**
1. Create a file called `test.php` with the code sample above...
2. Run `phpcs test.php ...`
3. See error message displayed
```
Squiz.ControlStructures.ControlSignature.SpaceAfterCloseParenthesis: Expected 1 space(s) after closing parenthesis; found 0
```

**Expected behavior**

`phpcs` must ignore alternative syntax of control structures for standard PSR-12.

**Versions (please complete the following information):**
 - OS: Windows 10
 - PHP: 7.3
 - PHPCS: master
 - Standard: PSR12

**Additional context**

**Comment by jrfnl** [comment]
PSR12 section 5 has rules about control structures. As far as I can see, there is no mention anywhere that those rules do not apply in the same way for control structures using alternative syntax, so I don't think this is a bug.

Ref: https://www.php-fig.org/psr/psr-12/

**Comment by WinterSilence** [comment]
@jrfnl yes, but why `<?php foreach ($fields as $field): ?>` must be replace to `<?php foreach ($fields as $field) : ?>`? PSR-12 don't told about this.

**Comment by gsherwood** [comment]
Section 5 of PSR-12 says:
>The body of each structure MUST be enclosed by braces. This standardizes how the structures look and reduces the likelihood of introducing errors as new lines get added to the body.

So alternative syntax is could be considered banned and the PSR12 standard in PHPCS could be adjusted to error for every usage, but I didn't do that for PSR2 so I also didn't do it for PSR12. I think that part of the standard is more focused on inline control structures and not alternative syntax, which is why I don't throw errors.

Either way, if you want to use alternate syntax, you can either format the code structures in the same way as normal brace syntax or have PHPCS ignore those templates files or code sections.
