### ISSUE TITLE
Unable to run php --generator

### ISSUE THREAD

**Issue by Temepest74** [squizlabs/PHP_CodeSniffer#3500]
When I run `phpcs --standard=PSR12 --generator=text`
I get this error:
```
PHP Fatal error:  Uncaught Error: Class 'PHP_CodeSniffer\Generators\text' not found in /usr/share/php/PHP/CodeSniffer/src/Runner.php:92
Stack trace:
#0 /usr/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#1 {main}
  thrown in /usr/share/php/PHP/CodeSniffer/src/Runner.php on line 92
```

**Comment by jrfnl** [comment]
I presume @Temepest74 figured this out already, but in case someone else is running into this: the issue here is one of a case-sensitive operating system. IF the OS is _not_ case-sensitive, the above works fine. IF it is, the correct case needs to be used for certain CLI arguments which map to classes.

```bash
phpcs --standard=PSR12 --generator=Text
phpcs --standard=PSR12 --filter=GitStaged
```
