### ISSUE TITLE
"fix the whole file" not working in PhpStorm

### ISSUE THREAD

**Issue by wturrell** [squizlabs/PHP_CodeSniffer#3545]
How can I debug this?

When using F2 in PhpStorm to jump to the next error, for phpcs errors it'll give a shortcut labelled:

> PHP Code Beautifier and Fixer: fix the whole file

Frequently this just won't do anything at all. Very occasionally it might fix one error on current line.  

I tried upping the Tool process timeout setting from 5 seconds to the maximum of 60, but **I'm not seeing any warnings or errors** in PhpStorm's error log window, or in idea.log. If I switch to Activity Monitor I don't see phpcs in the process list.

phpcs *is* always correctly identifying errors.

For context, I'm currently refactoring a file in a Laravel app and I have currently have just over 40 'weak warnings', around 20 of which are from phpcs. I'm also using phpmd. I have PHP CS Fixer turned *off* in Quality Tools.

**Versions (please complete the following information):**
 - OS: macOS 10.15.7 (Catalina)
 - PHP: 8.1.1
 - PHPCS: 3.6.2
 - Standard: PSR12
 - PhpStorm: 2021.3.2 (PS-213.6777.58 Jan 31 2022)

**Comment by jrfnl** [comment]
I'd suggest trying to run `phpcbf` on the command line for your project to see what the output is.

If things run smoothly on the command line, the problem is the PHPStorm integration. In that case, please contact PHPStorm support as there is nothing which can be done here.

If it ends up with a "failed to fix", try running it with `-vvv` to see which sniffs are in conflict and to isolate the problem code.
Fixer conflicts can be caused by ruleset configuration issues (including two sniffs with contradicting rules) or by an actual problem with sniffs which shouldn't conflict.
So, once you know what the conflicting rules are, check your configuration and if it's not a configuration issue, please report the conflict with a code sample + ruleset sample with which the issue can be reproduced.

**Comment by wturrell** [comment]
Fixed by configuring the path to phpcbf separately in the preferences. Sent an email to Jetbrains about it.
