### ISSUE TITLE
Latest codesniffer compatibile with PHP 8.1.3? 

### ISSUE THREAD

**Issue by Sweepr** [squizlabs/PHP_CodeSniffer#3548]
Tried to run PHPCS using Scrutinizer on PHP 8.1.3 and it crashed due to some incompatibility issue's, see attached: https://pastebin.com/KnQJYpYk

FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 1 | ERROR | An error occurred during processing; checking has been
   |       | aborted. The error message was: trim(): Passing null to
   |       | parameter #1 ($string) of type string is deprecated in
   |       | /home/scrutinizer/build/vendor/phpcompatibility/php-compatibility/PHPCompatibility/Sniff.php
   |       | on line 131

**Versions (please complete the following information):**
 - PHP: 8.1.3
 - PHPCS: 3.6.2

**Additional context**

Pastbin with full error log: https://pastebin.com/KnQJYpYk

**Comment by jrfnl** [comment]
@Sweepr PHP_CodeSniffer itself is runtime compatible with PHP 8.1. Note: not all PHP 8.1 syntaxes are supported yet.

While PHPCS may be runtime compatible, that does not mean that all external standards have released a version yet which is runtime compatible with PHP 8.1.

The issue above has [already been fixed in the downstream external standard](https://github.com/PHPCompatibility/PHPCompatibility/pull/1276) you are using, but has not been included in a new release of that external standard yet.

**Comment by Sweepr** [comment]
Great to hear it is already fixed, so it is just a matter of time and wait for the external parties to update their official releases, am i right?

**Comment by jrfnl** [comment]
@Sweepr Indeed. In the mean time, you could try using the `develop` version (if you dare).
