### ISSUE TITLE
PEAR.Functions.FunctionCallSignature incorrect indent fix when checking mixed HTML/PHP files

### ISSUE THREAD

**Issue by giorgosbotis** [squizlabs/PHP_CodeSniffer#3666]
running phpcbf on a file containing the following code:
``` 
<?php include get_theme_file_path(
        '/theme_extra/test_block.php'
      ); ?>   
```

I get the following error:
`Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined array key -1 in /app/myproject/vendor/squizlabs/php_codesniffer/src/Fixer.php on line 510 in /app/myproject/vendor/squizlabs/php_codesniffer/src/Runner.php:604`

**Comment by gsherwood** [comment]
I can't replicate this issue. What coding standard are you using and with what PHPCS version?

**Comment by giorgosbotis** [comment]
Sorry for not adding info:
phpcs 3.7.1
php 8.0.19
`phpcbf --standard=PEAR ./test.php`

**Comment by gsherwood** [comment]
Thanks, have managed to replicate. Doesn't appear to be tab related, but the indent is important.

**Comment by gsherwood** [comment]
So the issue here is the indent before the open PHP tag. If it's divisible by the indent size (normally 4 characters) then you wont get an error message and nothing will try to be fixed.

If it's not (I believe the example code has 6 spaces on indent) then it will try and bring the indent back in line with a tab stop. When it did this with inline HTML (anything outside the PHP tags) it did the fix incorrectly and removed content. If the content was the first thing in the file, you get the error message in this bug report.

The fix I'm committing will still report the same error message, but the auto-fixer in PHPCBF will now treat inline HTML differently so it can apply the fix properly.

**Comment by gsherwood** [comment]
I've committed a fix for this issue, which will be in the 3.7.2 release. Thanks a lot for reporting it.

**Comment by jrfnl** [comment]
Looks like the OP also reported this (with a different description) in https://github.com/WordPress/WordPress-Coding-Standards/issues/2083 for which I opened PR #3667....

**Comment by giorgosbotis** [comment]
It was reported with a different description, as there were two different issues I encountered. 

The one reported here was getting an exception running cbf with PEAR standard only, while the other one was Worpdress-Core standard producing wrong code (no exception there).

I am sorry but I had no clue they were connected or the same.
