### ISSUE TITLE
Add optional support for Tab indentation to sniffs

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#380]
Currently there are at least 10 sniffs that auto-fix indentation using spaces (e.g. `PSR2_Sniffs_Classes_ClassDeclarationSniff` and `PEAR_Sniffs_Classes_ClassDeclarationSniff`).

I've extracted padding generation code from `ScopeIndent` sniff and I can apply it to other sniffs as well if needed.

**Comment by gsherwood** [comment]
There is no need to have sniffs written for tab or space indent. All sniffs should assume space indents and allow another sniff in the coding standard to enforce and fix the indent to what it should be. The tab-width setting should be used to tell PHP_CodeSniffer to replace tabs with spaces.

The only sniffs that really need to consider the indent style in 2.0+ are the DisallowSpaceIndent and DisallowTabIndent sniff (for obvious reasons) and the ScopeIndent sniff because it does the actual replacement and alignment of indents. If you have written you own sniff to replace one of these, it would obviously need to consider the indent type as well.

All other sniffs can just use a 4-space indent when they are fixing code and allow one of the 3 above sniffs to fix that indent for them. This would include your custom sniff as well. Let the other sniffs decide how to fix your padding so people can use whatever tab-width they want (4 and 2 are obviously the most popular).

I'm going to close this because I don't want to encourage developers to write indent-aware sniffs. It is difficult, error-prone and may conflict with the 3 main indent checking sniffs. But if you find yourself needing all these methods a lot, then you should be able to achieve sub-classing in your custom standard.

**Comment by aik099** [comment]
> There is no need to have sniffs written for tab or space indent. All sniffs should assume space indents and allow another sniff in the coding standard to enforce and fix the indent to what it should be. The tab-width setting should be used to tell PHP_CodeSniffer to replace tabs with spaces.

I'm already using `tab-width` command line option of course. What I'm saying is that same sniff which detected indentation issue should be responsible for fixing it (because it already know needed $stackPtr and other info).

> The only sniffs that really need to consider the indent style in 2.0+ are the DisallowSpaceIndent and DisallowTabIndent sniff (for obvious reasons) and the ScopeIndent sniff because it does the actual replacement and alignment of indents. If you have written you own sniff to replace one of these, it would obviously need to consider the indent type as well.

There is where I got infinite fixing loop:

1. the `FunctionDeclaration` sniff indented multi-line function declaration using `4 spaces`
2. then `DisallowSpaceIndentSniff` kicked in and replaced `4 spaces` with `1 tab` (which to him is equivalent of `1 space` later on)
3. then `FunctionDeclaration` sniff kicked in again (in another fixing loop) because it saw function indented with 1 tab and not 4 spaces and replaced it again with 4 spaces
4. then `DisallowSpaceIndentSniff` kicked in and replaced `4 spaces` with `1 tab` (which to him is equivalent of `1 space` later on)
5. and I got infinite fixing loop

**Comment by gsherwood** [comment]
> There is where I got infinite fixing loop:

If you are using the tab-width setting, that shouldn't happen. Each time the file is parsed, tabs are replaced with spaces so that 1 tab would have been replaced by 4 spaces, and FunctionDeclaration would not see any problems the second time around.

I just tested this and it is working. I used this ruleset for testing: https://gist.github.com/gsherwood/9d22f634c57f990a7c64

This file:
```php
<?php

function foo(
$foo,
$bar,
$baz
) {
    echo 'hi';
}
```

And got this as the fixed file (note that they are tab indents), which required 3 passes and fixed 5 errors:

```php
<?php

function foo(
	$foo,
	$bar,
	$baz
) {
	echo 'hi';
}
```

**Comment by aik099** [comment]
Thanks for testing. Then I haven't used `tab-width` argument during fixing and relied on fact, that it has it's defaults for fixing to 4. But unfortunately that wasn't replacing 1 tab into 1 space when reading file before fixing. Then I could have got that infinite loop.
