### ISSUE TITLE
PHP 8.2 support release

### ISSUE THREAD

**Issue by janedbal** [squizlabs/PHP_CodeSniffer#3864]
Hi, is there any checklist what needs to be done before new release with PHP 8.2 support is tagged? 

When an [contributor update announcement was made](https://github.com/squizlabs/PHP_CodeSniffer/issues/3814) in May, it felt like this package is being revived, but no release occurred since then. Many people [volunteered](https://github.com/squizlabs/PHP_CodeSniffer/pull/3728#issuecomment-1554006691) and many PHP 8.2 PRs are already merged. I'd really like to start using readonly classes in my projects, maybe I could help with some of the remaining issues.

Thank you.

**Comment by jrfnl** [comment]
Well, without judgement - people may have volunteered, but that doesn't mean they subsequently did anything/started contributing...

Having said that, the biggest help at _this_ moment, would be people testing (and possibly reviewing) open PRs and confirming that those fix what they claim to fix without side-effects.
Issue triage on the open issues is also helpful.
The contributing guide in (open) PR #3830 contains some info on how to get started with either.

I've merged a number of PRs since my elevation to co-maintainer, but, as I've stated before, I will not merge my own PRs, so especially confirmation on those is helpful as it will inform the person who needs to merge those.

As for a release, I currently don't have much insight into the release process (see #3844). Once more information becomes available about that, I'll be looking to automate the process as much as possible to allow for more rapid releases in the future.

For now, until the other maintainer has time again, we'll just have to be patient.

**Comment by janedbal** [comment]
Thanks. 

Looking at your contributions, I see huge amount of effort and I really look forward to all those improvements. But currently, I really think people most care about:
- inability to use new PHP features
- broken stuff

To keep this library alive and popular, I think the efforts should be put into those fields.

----

So, is there any missing PHP 8.2 feature not covered in master?

**Comment by jrfnl** [comment]
> To keep this library alive and popular, I think the efforts should be put into those fields.

What do you think we are doing priority wise ?

**Comment by jrfnl** [comment]
> So, is there any missing PHP 8.2 feature not covered in master?

Yes, DNF is not handled at all yet and will probably need tokenizer changes too, but that's not for the faint of heart.

**Comment by janedbal** [comment]
> What do you think we are doing priority wise ?

I dont know, I'm not keeping close eye on the development here, I just saw quite a few pulls about performance / PHP 8.3 / contributing / security :)

**Comment by jrfnl** [comment]
> I just saw quite a few pulls about performance / PHP 8.3 / contributing / security :)

Well, the contributing/security etc PRs are to help make it more straight forward for all those people offering help to actually start doing so.

As for the performance PRs: considering how many people use PHPCS on a daily basis, including in CI, any significant performance improvements will lead to an exponential amount of dev wait-time saved + CI time speed up (and possibly cost savings), so I do kind of think those are important, though as you may also notice, those PRs aren't currently [milestoned for the 3.8.0 release](https://github.com/squizlabs/PHP_CodeSniffer/milestone/31), while straight up bug fixes and PHP 8.2 support PRs are.

**Comment by olsavmic** [comment]
@jrfnl All contributions are for sure very much appreciated and speedup / security is as important. 

The situation could be greatly improved though if the tracking of milestones was not tied to specific release versions but rather just "PHP 8.2 language feature support", with continual releases.
 
The goals in current 3.8 milestone seem very much unrelated and since the release seems basically stuck, the **contributors** are **discouraged** as their work won't have much effect until a year later when all (unrelated) goals are finished.

Most of these bug-fixes could be fixed in minor releases. 

---

I understand maintenance of OS is difficult and I really appreciate someone took this great library that the whole community uses under their wings! Thank you! 

It's just that people contributing to open-source usually fix what bugs THEM and do not invest the time in fixing something unrelated just to get their already fixed feature released :/

**Comment by jrfnl** [comment]
@olsavmic Please read my earlier responses about rapid releases and not merging my own PRs etc. It's easy to criticize, but there really isn't much more that I can do.

**Comment by DannyvdSluijs** [comment]
@jrfnl Thanks for the efforts in trying to keep the tool alive. I've been going through a couple of your PR's as requested (marked for version 3.8.0 release) and approving where I deemed fit. In the upcoming weeks I hope to find some more time to review some more but also didn't want to bump your workload to much ATM.

Feel free to drop some instructions on how I (others as well) could even be more helpful in progressing that next release.

**Comment by jrfnl** [comment]
@DannyvdSluijs Thank you for doing those reviews. That should help to get those PRs merged.
I imagine it could be helpful to indicate in the approval message how you reviewed the PR, i.e. code review only or did you test the change on the CLI (via PHAR/clone) or ... ?

**Comment by janedbal** [comment]
> I will not merge my own PRs

I think you should.
