### ISSUE TITLE
The @codingStandardsIgnoreStart has no effect during fixing

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#415]
Code block marked with `// @codingStandardsIgnoreStart` and `// @codingStandardsIgnoreEnd` comments was fixed never the less.

I wonder how that's even possible knowing that no error was reported in that code block after I've added these special comments around it.

**Comment by gsherwood** [comment]
This is because those ignore flags and only used to remove errors after a run, before the errors are reported. I need to change that to check the ignored lines every time an error or warning is generated.

Thanks for finding this.

**Comment by gsherwood** [comment]
I remember why it is done like this now. A sniff like ScopeIndent will got through a whole file finding reporting issues. PHPCS hasn't yet processed those lines itself, so it doesn't know where those start/end ignore points are yet. After processing is complete, it removes the errors and warnings that were generated on the ignored lines. This saves a pass through the file before checking looking for ignore points, which are rarely used.

I'm not sure how best to fix this yet, without affecting performance.

**Comment by aik099** [comment]
Maybe you can always return `false` from `addFixableError`/`addFixableWarning` when line in error falls in range of these comments?

**Comment by gsherwood** [comment]
> Maybe you can always return false from addFixableError/addFixableWarning when line of token in error falls in range of these comments?

It doesn't work like that unfortunately. By the time the main file parser gets to the comment, some sniffs have already processed the entire file. Many sniffs start at the opening PHP tag and then process the file themselves rather than being woken up each time a bit of whitespace is found.

ScopeIndent is a good example. It does a complete run through each file once to record the structure and find the indents. When it finishes, the main file parser is only at the second token (the one right after `<?php`) and so it hasn't parsed any comments yet. But by this time, the fixes for indents have already been performed.

What I need to do is either get those sniffs like ScopeIndent to check for the comments themselves, or find a way to revert a fix after it has been done. I don't really like either of those two options, so I'll need to play around and see which one is less bad.

**Comment by gsherwood** [comment]
The way I decided to fix this is the pre-parse the file and determine the ignored lines. I piggy-backed off another method that actually sets the lines numbers so I didn't have to loop through a second time. This should result in no performance decrease, but the functionality now works during fixing as well.

**Comment by aik099** [comment]
Thanks.
