### ISSUE TITLE
Allow more than one standard when using Phing

### ISSUE THREAD

**Issue by andrewholgate** [squizlabs/PHP_CodeSniffer#468]
Configuring Phing to use multiple standards, such as `standard="Drupal,DrupalStrict"` returns the error:
`ERROR: the "Drupal,DrupalStrict" coding standard is not installed.`

This same configurations works when using PHPCS via the command line.

**Comment by gsherwood** [comment]
I don't have anything to do with Phing or the PHPCS Phing task. You'll need to open a bug report over on that project to get it fixed. If there is something they need from PHPCS to support this, they can post a feature request over here and I'll definitely take a look. But I think everything should be fine to support an array of standards instead of a single string.

**Comment by andrewholgate** [comment]
Apologies, you're right. I have opened the [request with the Phing community](http://www.phing.info/trac/ticket/1170).

**Comment by gsherwood** [comment]
Not a problem. Thanks for posting the link.
