### ISSUE TITLE
"Commenting.InlineComment" sniff restriction on end char validation

### ISSUE THREAD

**Issue by aik099** [squizlabs/PHP_CodeSniffer#505]
In the "Commenting.InlineComment" sniffs (in various standards) the start char is validated to be an uppercase letter only, when it's lowercase letter.

I propose that we only validate end char to be dot, exclamation mark, etc., when first char is uppercase letter. This way commented code like below won't cause any trouble:

```php
// $this->is->commentedCode();
```

**Comment by aik099** [comment]
Not related, but now we can also auto-fix 1st lowercase letter of inline comment to be uppercase.

**Comment by gsherwood** [comment]
Seems like a good change.

**Comment by aik099** [comment]
Which one, in issue description or in comment after that?

For proposal in task description wrapping https://github.com/squizlabs/PHP_CodeSniffer/blame/master/CodeSniffer/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php#L265-L282 with `if (preg_match('|\p{Lu}|u', $commentText[0]) === 1) {` should do it I guess.

**Comment by aik099** [comment]
> Not related, but now we can also auto-fix 1st lowercase letter of inline comment to be uppercase.

This might be tricky for RTL languages (because I guess last letter in comment is first letter for them), but currently validation part also doesn't account for that. Anyway there is no way to determine if it's RTL language or not just based on comment text.

**Comment by gsherwood** [comment]
I've made the change so that the last char is not checked if the first char is not a letter. I couldn't find other sniffs that would allow debug code to be used like this (docblocks enforce proper sentences because they are used in docs).

I did not auto-fix the first character though. I'm not really sure I want to change non-PHP content written by the developer in case something is incorrect. Changing syntax and whitespace is easy and generally risk-free. Maybe I'm being too paranoid.
