### ISSUE TITLE
Find phpcs.xml config file in parent directories

### ISSUE THREAD

**Issue by petersendidit** [squizlabs/PHP_CodeSniffer#626]
If you run `phpcs` from a directory below the level that the phpcs.xml file is phpcs doesn't use that config.

After using eslint for a while I have gotten use to being able to call the `eslint` command from any directory and it honoring the `.eslintrc` config.  Eslint handles this with a `findInDirectoryOrParent` method:  https://github.com/eslint/eslint/blob/master/lib/file-finder.js#L57

This would help editors also to be able to easily pick up the phpcs.xml config

**Comment by gsherwood** [comment]
This is something I want to do, but it's not as simple as just looking up the tree because I want to combine this with the other related feature people ask for, which is to have PHPCS change standards when it finds a phpcs.xml file inside a directory. This allows you to have slightly (or completely) different standards for various parts of the codebase, which is helpful if you are including libraries, or want different standards for integration code or unit tests.

This will probably only get added to the 3.0 version because it would be a lot easier with the refactoring I've done in the 3.0 branch.

**Comment by gsherwood** [comment]
I decided that it would be better to not do this feature with the one that allows different standards in different parts of the tree. This new feature is now committed.
