### ISSUE TITLE
Add trailing comma in arrays? 

### ISSUE THREAD

**Issue by huglester** [squizlabs/PHP_CodeSniffer#629]
Hello,

I wonder, how do I tell codesniffer to add trailing commas to arrays?

So this:
```php
array(
    '1',
    '2'
);
```

would be converted to this:
```php
array(
    '1',
    '2', <-- note a comma
);
```

Thanks!

**Comment by orlangur** [comment]
This sniff can be used: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php#L850

Just add this sniff to your standard similar to https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/PHPCS/ruleset.xml#L11 declaration.

**Comment by gsherwood** [comment]
There is no sniff that will only add trailing commas to arrays, but leave the rest of the array untouched. I'll leave this as a feature request for one as it would be quite useful.

**Comment by orlangur** [comment]
@huglester, if the rest of array must remain unchanged `multiline_array_trailing_comma` from https://github.com/FriendsOfPHP/PHP-CS-Fixer could be used.

@gsherwood, you mean separate sniff creation or flexible mechanism to customize any sniff behavior?

For example, we have few error codes used in sniff
```
$fix   = $phpcsFile->addFixableError($error, $index['value'], 'NoComma');
$fix   = $phpcsFile->addFixableError($error, $trailingContent, 'NoCommaAfterLast');
$fix   = $phpcsFile->addFixableError($error, $value['value'], 'ValueNoNewline');
```
Instead of `<rule ref="Squiz.Arrays.ArrayDeclaration" />` some 
`<rule ref="Squiz.Arrays.ArrayDeclaration.NoComma" />`
 or 
```
<rule ref="Squiz.Arrays.ArrayDeclaration">
    <error code="NoComma" />
</rule>
```
could be used to ignore all error codes except this one.

**Comment by gsherwood** [comment]
> @gsherwood, you mean separate sniff creation or flexible mechanism to customize any sniff behavior?

I meant a new sniff to just check and fix this because it seems like a few people want it. The ability to include single message codes only (and ignore the rest of the sniff) was added to the 3.0 branch last week but I can't backport that as it is a bit too risky for a stable version. The syntax for including the message in your ruleset is: `<rule ref="Squiz.Arrays.ArrayDeclaration.NoComma" />`

**Comment by paulschreiber** [comment]
I would find this very handy. I just committed a diff with about 300 comma changes in it. :/

**Comment by orlangur** [comment]
@gsherwood, if I understood you correctly such feature will be available in version 3.0 out of the box.

Then why it is needed as enhancement in 2.x?

**Comment by gsherwood** [comment]
> Then why it is needed as enhancement in 2.x?

Because I think that breaking out some of the more generic checks from the big Squiz array sniff would ultimately be better.

**Comment by gsherwood** [comment]
Closing this in favour of #582 , which includes this and other enhancements.
