### ISSUE TITLE
Some class names cause CSS tokenizer to hang

### ISSUE THREAD

**Issue by mathieuchateau** [squizlabs/PHP_CodeSniffer#636]
Hello,

While processing still same site as issue before, phpcs hangs, apparently forever, on a css file.

Even when trying phpcs with just this file, still no progress after 15mn:

phpcs -v -d memory_limit=2048M /path/to/bootstrap-switch/static/stylesheets/bootstrap-switch.css
Registering sniffs in the PEAR standard... DONE (27 sniffs registered)
Creating file list... DONE (1 files in queue)
Changing into directory /path/to/bootstrap-switch/static/stylesheets
Processing bootstrap-switch.css

that's it, it stay on this line, eating 100%cpu of one core.
it's a 408 line CSS, here is the source of it:
https://gist.github.com/mathieuchateau/b561a361dbfb44f0830b

I am more worried that it can litterally block phpcs than quality of this css

**Comment by gsherwood** [comment]
Thanks for posting the file. The tokenizer itself wasn't hanging forever; it was backtracking every time it saw the "switch" string because it piggy-backs off the PHP tokenizer. I've added more PHP constructs to the CSS blacklist so the tokenizer doesn't try to process them, which fixes this file, and hopefully all others like it.
