### ISSUE TITLE
"No PHP code was found in this file" in HTML file

### ISSUE THREAD

**Issue by powelski** [squizlabs/PHP_CodeSniffer#643]
In pure HTML files with .html extension, I'm getting a following error: `No PHP code was found in this file`. PHP code  was not meant to be there, so why is this error showing in HTML file?

**Comment by aik099** [comment]
I guess in some web server configurations HTML files are allowed to contain PHP code, like PHTML files. Therefore PHP_CodeSniffer is checking them as well. I recommend specifying `--extensions php` in command that you use to run `phpcs` to only look for PHP files.

**Comment by powelski** [comment]
Thanks for explanation. I don't understand the reason of this warning, what happens if we have a file without PHP code? Why does the user need to be informed about it?

**Comment by gsherwood** [comment]
PHP_CodeSniffer doesn't check `.html` files by default. If you don't specify any file extensions, the defaults it looks for are `.php`, `.inc`, `.js` and `.css`. This list is here: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer.php#L173

The only exception to this is if you tell PHPCS to check a `.html` file directly, as in
 `phpcs /path/to/file.html`

In this case, PHPCS will check the file because it assumes you know what you are doing, or you have some other reason to check it (embedded PHP maybe).

So why is PHPCS checking your HTML files?
- Maybe your custom coding standard specifies file extensions, and lists `.html` as one of them
- Maybe you are using a plugin for a text editor and it is checking the file directly, either by filename or using STDIN
- Maybe you are checking files individually using some sort of script or build system

Any of those scenarios sound possible?

**Comment by powelski** [comment]
I'm using PHP Code Sniffer as a plugin for Sublime Text :)

**Comment by gsherwood** [comment]
> I'm using PHP Code Sniffer as a plugin for Sublime Text :)

That might be the problem then. You'll need to tell the plugin what file extensions you want it to check (I assume it has this feature) otherwise PHPCS will check whatever files it is told to.

Does that solve the problem?
