### ISSUE TITLE
PEAR ScopeClosingBrace sniff does not work with mixed HTML/PHP

### ISSUE THREAD

**Issue by powelski** [squizlabs/PHP_CodeSniffer#644]
I'm getting an error when I use a mix of PHP alternative syntax and `endforeach`, like this:
```php
<ul>
    <?php foreach ($array as $value) : ?>
        <li><?php echo $value ?></li>
    <?php endforeach ?>
</ul>
```
The error message is `Closing brace must be on a line by itself` and it points out the line with `endforeach`. It disappears when I delete indentation of this line.

**Comment by gsherwood** [comment]
It's not the alternate syntax that causes this (it happens with standard syntax as well) but rather the mixing of PHP and HTML like you would in a template file. The built-in standards that PHPCS has don't work very well with template files because they were written for standard include files.

But in this case, I think I can get the sniff to ignore this syntax without affecting anything else.

**Comment by gsherwood** [comment]
I've made this sniff support mixed HMTL/PHP syntax now.
