### ISSUE TITLE
Long sniff codes can cause PHP warnings in source report when showing error codes

### ISSUE THREAD

**Issue by GaryJones** [squizlabs/PHP_CodeSniffer#694]
When running a source report, as part of [`grunt phpcs`](https://github.com/SaschaGalley/grunt-phpcs), I'm getting the report generated at https://gist.github.com/GaryJones/156f24e88c71ab453937

> Warning: str_repeat(): Second argument has to be greater than or equal to 0 in .../phpcs/CodeSniffer/Reports/Source.php on line 201

This appears to happen with multiple (but not all) sniffs from WordPress, Squiz and Generic standards, all in use by the WordPress standard.

It only happens with Source reports. Full, Summary and Info reports are all fine. If I run `phpcs` directly, not with grunt, then the errors do not appear, but there's very little in the [grunt-phpcs code](https://github.com/SaschaGalley/grunt-phpcs/blob/master/tasks/phpcs.js) to suggest why these errors are appearing.

phpcs: 2.3.4
grunt-phpcs: 0.4.0
grunt: 0.4.5

Here's my `phpcs.xml`:

```xml
<?xml version="1.0"?>
<ruleset name="Gary Jones">
	<description>The code standard for Gamajo theme.</description>
	<file>theme/.</file>
	<arg name="extensions" value="php"/>
	<arg name="report-full" value="logs/phpcs-full.log"/>
	<arg name="report-summary" value="logs/phpcs-summary.log"/>
	<arg name="report-source" value="logs/phpcs-source.log"/>
	<arg name="report-info" value="logs/phpcs-info.log"/>
	<arg value="sp"/>
	<exclude-pattern>vendor/.</exclude-pattern>
	<rule ref="WordPress.XSS.EscapeOutput">
		<properties>
			<property type="array" name="customAutoEscapedFunctions" value="genesis_attr"/>
		</properties>
	</rule>
	<rule ref="WordPress">
		<exclude name="WordPress.VIP"/>
		<!--<exclude name="WordPress.Files.FileName.UnderscoresNotAllowed"/>-->
	</rule>
</ruleset>
```

Using load-grunt-config, my `phpcs.js` is:

```js
module.exports = {
	options: {
		// Assumes 'phpcs' is accessible in the global system.
		// If not, set 'bin: /path/to/bin/phpcs'
		// ignoreExitCode: true,
		standard: 'phpcs.xml'
	},
	src: [
		'<%= paths.theme %>**/*.php'
		]
	}
};
```

It also happened with:

```js
module.exports = {
	options: {
		// Assumes 'phpcs' is accessible in the global system.
		// If not, set 'bin: /path/to/bin/phpcs'
		// ignoreExitCode: true,
		standard: 'phpcs.xml'
	},
	full: {
		options: {
			reportFile: '<%= paths.logs %>phpcs-full.log'
		},
		src: [
			'<%= paths.theme %>**/*.php'
		]
	}
};
```

**Comment by aik099** [comment]
Do you see same errors when running `phpcs` command by hand and telling to report in source format?

**Comment by GaryJones** [comment]
> Do you see same errors when running phpcs command by hand and telling to report in source format?

I don't think so, no.

**Comment by gsherwood** [comment]
This happened if you were using a non-auto report width (default is 80) with a sniff code that was almost as long.

The reason you may not have seen the error when running manually could be due to PHPCS using the auto width setting and being able determine the terminal width. It may not have been able to determine it in the CI run, and so used the default value there.

With this fix, your sniff codes will be cut off. If you'd prefer to see the whole thing, add this to your ruleset: `<arg name="report-width" value="90"/>` and adjust up if you get any more errors. You can set it to something higher if you'd like, but it just means your other reports (especially the full report) will wrap at a different location. That might be good or bad.

**Comment by GaryJones** [comment]
Thanks for the fix to a slightly obscure bug.
