### ISSUE TITLE
Allow auto-fixing for AbstractPattern sniffs

### ISSUE THREAD

**Issue by AbdealiJK** [squizlabs/PHP_CodeSniffer#700]
Add a callback in AbstractPatternSniff - something like `onErrorFound` with various args which can be useful to devs.

This would be needed if I want the abstract pattern sniffer to automatically fix patterns for me.

Example, I have a test with `if(1)` while it should be `if ( 1 )`. AbstractPatternSniff can already tell the "found" and "pattern" - so, it shouldn't be hard to make a fixer for it.
The callback would allow me to make a fixer.

**Comment by gsherwood** [comment]
It would actually be really hard to make a proper fixer for the AbstractPatternSniff, which is why I migrated some of my sniffs away from it when I was building PHPCBF. If you want accurate fixes, you'll really need to create a standard sniff looking for the patterns you want.

Here is the best example I can find of that right now: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php
And the commit where I converted it over: https://github.com/squizlabs/PHP_CodeSniffer/commit/7cb5dce5263dd0de27e995a8fbae4766dbc8e7ea

**Comment by AbdealiJK** [comment]
Would it be that difficult to make a general fix for the formats ?
Could you describe what osrt of issues would crop up ?
I may be missing something very obvious.

**Comment by gsherwood** [comment]
> Could you describe what osrt of issues would crop up ?

The fixer works on tokens, not raw strings. So if you have something like `if(` that needs to be replaced by `if (` you need to figure out what token the `if` is and then add a space after that. You can't just do a string replacement because you have no token to target.

**Comment by AbdealiJK** [comment]
Ah - I see. That would get complicated.

Thanks !

**Comment by gsherwood** [comment]
Closing as I can't see how this could ever be implemented correctly.
