### ISSUE TITLE
Question: Can I use CodeSniffer via PHP instead of the command line?

### ISSUE THREAD

**Issue by natanmoraes** [squizlabs/PHP_CodeSniffer#741]
Hello.

I'm working on a project that should do the following:
1. Get a file uploaded by the user
2. Sniff the file with a custom standard
3. Process the result

At the moment, I'm doing item # 2 above with plain old `exec()` from PHP calling `phpcs` and I'm wondering if that's the proper way.

Can I use `CodeSniffer.php` to do that instead? I mean, can I call `new PHP_CodeSniffer()` and work with it? Better yet, *should* I do that?

If I can, is there any examples on how I can use that class?

Thanks in advance

**Comment by gsherwood** [comment]
Technically, I guess you can because the phpcs script does just that and I am fairly sure at least 1 other person has done it before. But version 2 isn't built for that and I have no examples of it working. I imagine you'd get fairly frustrated, but you could make it work.

Version 3 has been refactored to make this much easier. A good example is the ability to inject your own Config object into the run rather than having to fudge the CLI values. But that version is not ready for release yet (it's the 3.0 branch in this repo).

The worse news is that anything you do in this area for version 2 will need to be rebuilt when version 3 does eventually come out. They are completely different.

Summary: Yes, you can do it. It will be hard (I'm happy to help). It will be intentionally easier in version 3, but there is no release date for that.

**Comment by natanmoraes** [comment]
Ah, awesome news about v3.

I'll weigh my options and decide which approach I'll follow.

If I decide to use the class and run into any problems I'll let you guys know.

Thanks for the reply.

**Comment by orlangur** [comment]
@natanmoraes, in Magento 2 we used wrapper over `PHP_CodeSniffer_CLI` class to achieve this: https://github.com/magento/magento2/blob/develop/dev/tests/static/framework/Magento/TestFramework/CodingStandard/Tool/CodeSniffer.php#L98
