### ISSUE TITLE
Testing Custom Sniffs

### ISSUE THREAD

**Issue by PatrickRose** [squizlabs/PHP_CodeSniffer#743]
A project I'm working on is only just moving to composer, so we currently have PHPCS included manually via git clone. Our coding standard is also full of custom sniffs that I've created which are all backed up by tests. If we move PHPCS into composer, I'd lose the ability to test these sniffs.

I agree with previous people that the tests/ directory shouldn't be included - but how should we handle testing that our sniffs are working as intended? I'm not sure there's any documentation for it.

**Comment by gsherwood** [comment]
I don't use composer, so I'm really not sure if there is a way to both satisfy the people that don't want all the test and testing framework in their composer install, and those they want everything because they are developing sniffs for PHPCS.

The way you are doing it now (the git clone for development) is how I do dev, and so is my recommended way.

You might want to look into using composer for developers who don't actively work on custom sniffs, and then using a separate git clone for those that need to do development on it. Then make your custom standard also installable via composer and have your coding standard look for those sniffs in a relative location.

Ideally, you composer install everything, tell PHPCS where the custom standard is installed via a config option of CLI option, then everything will just work from there. Then if you want to dev sniffs, you use the git clone to get everything working and tested, then commit/push to your repo and composer update your installs.

But I'm talking very generally. I've never tried any of this.

**Comment by PatrickRose** [comment]
I think the only proper way would be a separate package that has a base for testing sniffs - and that sounds like a pain in the butt for you especially with be v3 on the way. If I do hack it out then I may as well just work with a git clone.

**Comment by gsherwood** [comment]
Maybe I'll just changed version 3 to include all the tests and see if anyone notices :)

**Comment by glen-84** [comment]
> Maybe I'll just change version 3 to include all the tests and see if anyone notices :)

I noticed! Just kidding.

But seriously, you should be able to use `--prefer-source` when installing PHPCS via Composer. That way, you'll get a clone with all the tests, etc.

`composer require squizlabs/php_codesniffer --dev --prefer-source`

**Comment by gsherwood** [comment]
> But seriously, you should be able to use --prefer-source when installing PHPCS via Composer

Good tip. Does that work for you @PatrickRose ?

**Comment by gsherwood** [comment]
> But seriously, you should be able to use --prefer-source when installing PHPCS via Composer

Related comment: https://github.com/squizlabs/PHP_CodeSniffer/issues/548#issuecomment-92573200
