### ISSUE TITLE
phpcs not exiting if no input files specified

### ISSUE THREAD

**Issue by JustTSK** [squizlabs/PHP_CodeSniffer#749]
If you run phpcs without input files specified,
```
phpcs --standard=.phpcs.xml -v
```
it got stuck on 
```
Creating file list... DONE (0 files in queue)
```
until you manually terminate it.

**Comment by aik099** [comment]
No input files specified means scan all files in current directory recursively.

**Comment by JustTSK** [comment]
But its not scanning anything at all.

**Comment by aik099** [comment]
Maybe according to `.phpcs.xml` file contents all files are excluded.

**Comment by JustTSK** [comment]
I'm not excluding any files in ruleset, but even if so, shouldn't it just
exit?

**Comment by gsherwood** [comment]
If you specify no files, PHPCS waits for STDIN. This is how plugins for text editors are able to check the contents of your file without you needing to save it.

In version 3.0 (no release date), I have changed PHPCS so that you need to pass `-` as an argument to have it wait for STDIN. Otherwise, it will report an error that there are no files to check. For reference, this was committed here: https://github.com/squizlabs/PHP_CodeSniffer/commit/5d0784a3351d7e04188005c8eec9dd829d5d481e

So from version 3.0, you'll get this:
```
$ phpcs --standard=mystandard.xml
ERROR: You must supply at least one file or directory to process.

Usage: phpcs [-nwlsaepvi] [-d key[=value]] [--cache] [--no-cache] [--colors] [--no-colors]
...
```

**Comment by JustTSK** [comment]
That makes perfect sense! Thanks for the explanation.
