### ISSUE TITLE
Squiz.PHP.CommentedOutCode can ignore '//end '-prefixed comments only

### ISSUE THREAD

**Issue by guillaume-d** [squizlabs/PHP_CodeSniffer#767]
A configurable list of ignored comment prefixes would be:
- useful
- easily made backward-compatible (just add `'//end '` to it)
- only as slow as one decides to make it by configuration

Suggestion for prefixes: `'//TODO'`, `'/*TODO'`, `'//FIXME'`, `'/*FIXME'`, `'//XXX'`, `'/*XXX'`, `'/*.'` (PHPLint's meta-code)

**Comment by gsherwood** [comment]
The only reason that the sniff has that particular pattern hard-coded is because (at least at the time) it was common to put comments in like `//end if` and `//end foreach` and `//end class`. These comments use PHP keywords (if, foreach, class) and so tokenize as up to 50% valid code and cause false positives almost every time.

I'm not sure what the point of adding prefixes for things like TODO and FIXME would be. They aren't used in the same way.

**Comment by guillaume-d** [comment]
I had a look at my use cases again and indeed it is not really needed for TODOs and FIXMEs.

For XXXs I need it sometimes to explain why some code is not written another way (which is still kept in the comments). Also it's hard to find a percentage which works well everywhere.

PHPLint's meta-code definitely needs this though: see http://www.icosaedro.it/phplint/phplint2/doc/reference/docblocks.htm#H18_When_PHPLint_meta-code_is_still_required

Besides I also use pseudo-annotations/tags in non-doc comments that I use to standardize some types of comments (and that would not validate as doc comments): they are very short and therefore very often look like code. I would need to ignore them too.

Also if "//end " is obsolete this would also give an easy way to get rid of that! :)

**Comment by guillaume-d** [comment]
Does the last label change means that a pull request could be accepted?

**Comment by gsherwood** [comment]
It just means I'm leaving it open for further discussion. But yes, I would of course consider a PR if you or someone else goes to the trouble of making one.

**Comment by gsherwood** [comment]
Closing as this doesn't look like it will ever happen.
