### ISSUE TITLE
False positives for Squiz.PHP.CommentedOutCode.Found

### ISSUE THREAD

**Issue by paulschreiber** [squizlabs/PHP_CodeSniffer#826]
This line is being flagged as commented-out code
```
	} // foreach $region
```

It's pretty common to do line comments at the end of `if` and `for` blocks like that. Please don't flag them.

Here's the whole block:
```php
	<?php
	foreach ( $quadrant as $region => $restaurants ) {
		// Grab the region color, used to get the winner id
		$region_color = $region_colors[ $region ];
		// Grab the winner id, used for the r_round_url
		$round_winner_id = self::round_winner_id( $quadrant_name, $region_color, $region );
	?>
	<div class="region-reviews <?php echo esc_attr( self::round_status( $quadrant_name, null, $region ) ), esc_attr( $region ); ?>">
....
	</div>
	<!-- .post -->
	<?php
	} // foreach $region
	echo '</div>';
	$i++;
} // foreach $quadrant
```

**Comment by gsherwood** [comment]
The only comments that sniff ignores are those that start with `// end`, as in:
```
  } // end foreach $region
```

I can't make exceptions for comments that start with real code tokens or else real commented out code is likely to get missed.

But this is also just a warning sniff, best used to aid manual code reviews. There isn't really a a good way for it to figure out if code is valid or note because even a syntax check would fail for many commented out blocks (e.g., conditions in a multi-line IF, or array indexes in a multi-line definition). So it will always report false positives and each comment will require manual review. That's also why it will never auto-fix anything it finds.

I'm sorry, but I don't think there is anything I can do for you that wont cause an issue elsewhere.

**Comment by bantu** [comment]
> I can't make exceptions for comments that start with real code tokens or else real commented out code is likely to get missed.

Am I missing something here? "Real commented code" is still a comment and as such not code and thus should not be detected by Squiz.PHP.CommentedOutCode.Found at all?

**Comment by aik099** [comment]
Ha, that's the point of the sniff - find commented out code.

**Comment by bantu** [comment]
Oh lol. Facepalm.

**Comment by gsherwood** [comment]
I don't think there is much I can do here, so closing. If anyone has any ideas, please comment and I'll reopen and take a look.

**Comment by kraftbj** [comment]
> The only comments that sniff ignores are those that start with `// end`, as in:

For anyone else finding this in the future, the sniff does ignore any code that begins with `//end` (without a space). [Code reference](https://github.com/squizlabs/PHP_CodeSniffer/blob/6016e2bc8fc1e0926f40271edb37aeb5d0a7b4fd/src/Standards/Squiz/Sniffs/PHP/CommentedOutCodeSniff.php#L65).
