### ISSUE TITLE
Issue with Squiz.Arrays.ArrayDeclaration.KeyNotAligned

### ISSUE THREAD

**Issue by YogeshJC** [squizlabs/PHP_CodeSniffer#853]
Hello,

I am having issues with Squiz.Arrays.ArrayDeclaration.KeyNotAligned.

I would like to write the array code as below. 

    public static $names = array(
        1 => Name1,
        2 => Name2,
    );

But running PHPCBF changes the code as shown below. 

    public static $names = array(
                            1 => Name1,
                            2 => Name2,
                           );

I would like PHPCBF to recognize the first format as standard in my code.

**Comment by aik099** [comment]
This is what mentioned sniff does. It's the format it expects. Unfortunately this is not configurable.

**Comment by YogeshJC** [comment]
What would be the process to follow in case there are nested arrays. 
When this standard is applied, PHPCBF automatically indents them in a way where it will cross the 80 character mark. 
This causes errors to show up when running PHPCS post the PHPCBF.

**Comment by aik099** [comment]
Maybe. As you can see the indentation rule is to:

1. put closing parenthesis of an array (`)`) at same deep level as where opening parenthesis is (`array(`)
2. the array content is indented 1 space after position of array opening

**Comment by gsherwood** [comment]
The sniff formats arrays in a very specific way for the Squiz standard. There are no other sniffs that check or format arrays because the other standards don't have any rules for array definitions at all.

Yes, the sniff will format arrays even if they go over 80 characters. This is just a warning by default, and the Squiz standard sets the line length higher anyway. It also cares more about the readability of the arrays than the length of the lines. But that's just that standard.

When it comes to arrays, you don't have any real options. I have an issue where I'm tracking potential new arrays sniffs here: https://github.com/squizlabs/PHP_CodeSniffer/issues/582
