### ISSUE TITLE
Move checks on scalar type hints (PHP 7) from Squiz.Commenting.FunctionComment.TypeHintMissing to a seperate rule

### ISSUE THREAD

**Issue by nicwortel** [squizlabs/PHP_CodeSniffer#858]
As stated in the title. The fact that I'm running PHP 7 doesn't mean that my code should exclusively run on PHP 7. Currently my build fails and I get a long list of errors like these:

> 26 | ERROR | Type hint "string" missing for $message

However, scalar type hints are a PHP 7 feature so I cannot use them as long as I need to support PHP 5.x.

So my request is to move the checks to a seperate rule (which I can exclude without also excluding all other type hint checks) instead of only checking whether I'm running PHP 7 or not.

**Comment by aik099** [comment]
You can exclude individual error messages while keep all other that sniff error messages active too.

**Comment by nicwortel** [comment]
@aik099 how? As far as I can see, I can exclude violations with the code `Squiz.Commenting.FunctionComment.TypeHintMissing`, but this will also disable violations for other type hints (such as arrays or class names, i.e. not the PHP 7 scalar type hints).

**Comment by aik099** [comment]
I thought you're talking about 2 different errors sniff produces. Now I see that it's the same error about method parameter type hint. No way to separate them now. But currently such checks are made only when you're on PHP 7+, so shouldn't be an issue unless you're running PHP 5.x code on PHP 7 web server, which I guess you're doing.

Moving checks to another sniff would double the job made to detect missing type hints in the first place so that might not be a good idea.

You really plan to maintain 2 standards (one for PHP 5 code and another one for PHP 7 code)?

I'm currently having same issue with `callable` type hints, that would end up in Fatal Error when used on PHP 5.3.

**Comment by aik099** [comment]
Probably best option would be to transform `Squiz.Commenting.FunctionComment.TypeHintMissing` error into `Squiz.Commenting.FunctionComment.TypeHintMissing.TypeNameHere` (e.g. `Squiz.Commenting.FunctionComment.TypeHintMissing.callable`). This should only work that way for build-in types (e.g. `callable`, `array`, `string`) so no error codes, like `Squiz.Commenting.FunctionComment.TypeHintMissing.NS1\NS2\MyCustomClass`.

**Comment by seggen-ibuildings** [comment]
I would argue that the change in 2.5.0 is a BC break as well. Suppose you have a library that you want Travis to test on both PHP 5 and PHP 7? Then you need to disable the sniff, because you would never get it to work on PHP 7 and compile in PHP 5 as well.

I have a suggestion, though. How about renaming Squiz.Commenting.FunctionComment.TypeHintMissing to Squiz.Commenting.FunctionComment.ScalarTypeHintMissing specifically for scalar type hints? You could then exclude this specific error, while keeping the sniff.

**Comment by nicwortel** [comment]
As Scato explained, this is a bug, not an enhancement.

**Comment by gsherwood** [comment]
> I have a suggestion, though. How about renaming Squiz.Commenting.FunctionComment.TypeHintMissing to Squiz.Commenting.FunctionComment.ScalarTypeHintMissing specifically for scalar type hints? You could then exclude this specific error, while keeping the sniff.

This sounds like a reasonable change to me.

**Comment by gsherwood** [comment]
> As Scato explained, this is a bug, not an enhancement.

It's not a bug; everything is working as intended. The different error cases are even coded into the unit test. But this intended functionality has an inherent limitation that @seggen-ibuildings has pointed out.

**Comment by gsherwood** [comment]
One thing that will need to be decided is if the errors should be the same on PHP5 and PHP7.

As there would now be two different error messages, it is possible to still generate `ScalarTypeHintMissing` while running on PHP5, going on the assumptions that you might want to run this code on PHP7 as well.

The other option (and my normal go-to option) is to only generate the new `ScalarTypeHintMissing` error while running on PHP7. So you'd get a different error report (more errors) when running on PHP7 than when running on PHP5. This would mean that you don't need to exclude `ScalarTypeHintMissing` from your ruleset because the errors just wouldn't show up on PHP5. It does mean that running PHPCS under PHP5 on PHP7-specific code would not generate the proper errors.

I prefer the second option, even though it forces you to run PHPCS under PHP7 if you are checking PHP7 code. It seems like a reasonable thing to except.

**Comment by gsherwood** [comment]
I've pushed a change to add this new error message and left everything else alone. The number of errors generated on PHP5 and PHP7 remain the same, but you can now exclude this message code if you want your code to run on both version.

Look ok?

**Comment by aik099** [comment]
:+1: for having different error code, because fact that PHP 7 is used doesn't mean that people must use scalar type hints.

**Comment by seggen-ibuildings** [comment]
Looks good. Thanks for picking this up. :smile:

**Comment by nicwortel** [comment]
Yes, thanks :+1:

**Comment by gsherwood** [comment]
Thanks for getting back to me.
