### ISSUE TITLE
Why are comments ignored for scope intention?

### ISSUE THREAD

**Issue by gimler** [squizlabs/PHP_CodeSniffer#898]
Why are comment intention ignored in PSR2 see 
https://github.com/squizlabs/PHP_CodeSniffer/commit/d8ed4e322a28203a7503302be4181c5f0f7b9e27

**Comment by aik099** [comment]
Maybe because PSR2 doesn't tell what to do with them and @gsherwood decided to ignore them for indentation.

**Comment by gsherwood** [comment]
Comments are ignored because every time a comment causes an error, it is (rightly) pointed out to me that PSR2 explicitly ignores all comments and comment blocks: https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#7-conclusion

So many sniffs need to treat comments as if they don't even exist. They are typically skipped over in the same way whitespace is.

If this frustrates you as much as it frustrates me, my suggestion is to create your own custom coding standard and put this check back in. But if you just want to follow PSR2, format and place your comments where ever you want; PSR2 doesn't care.
