### ISSUE TITLE
Add new sniff for strict _types declaration

### ISSUE THREAD

**Issue by Xerkus** [squizlabs/PHP_CodeSniffer#911]
New sniff for php 7 is needed to allow to enforce `declare(strict_types=1)`

**Comment by aik099** [comment]
Do you add this line in each PHP file or just in a bootstrap file of a project?

**Comment by Xerkus** [comment]
it is file local https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict

> Strict typing applies to function calls made from within the file with strict typing enabled, not to the functions declared within that file. If a file without strict typing enabled makes a call to a function that was defined in a file with strict typing, the caller's preference (weak typing) will be respected, and the value will be coerced.

**Comment by Xerkus** [comment]
In mixed content file, strict type declaration must be before anything non-php(fatal error otherwise):
```
<?php declare(strict_types=1); ?>
<html>
...
`

**Comment by aik099** [comment]
Feel free to send a PR adding that sniff to `Generic` standard when you're ready.

**Comment by gsherwood** [comment]
> Feel free to send a PR adding that sniff to Generic standard when you're ready.

Or leave this here as a feature request and I'll get around to it eventually.

**Comment by glen-84** [comment]
1. Would this include formatting? I prefer to use spaces around the equals sign (similar to default parameter values, etc.).
2. What about files that don't invoke any functions or methods – would it still make sense to require the declaration?

**Comment by sebastianbergmann** [comment]
I just missed this feature yet another time. Hope to get around implementing it next week.

**Comment by nicwortel** [comment]
@gsherwood / @sebastianbergmann any progress on this issue?

I think there should be a sniff for the existence of a `strict_types=1` declaration at the top of a file, as well as one for the formatting of it (usage of spaces).

[The draft of PSR-12 (Extended Coding Style Guide)](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) states that `declare` statements should not contain spaces, so that is probably a sensible default.

The question is of course if the second sniff (formatting) falls within the scope of this issue. Perhaps it is enough to start with the existence of the declaration, and add a sniff for the formatting later on.

**Comment by gsherwood** [comment]
> @gsherwood / @sebastianbergmann any progress on this issue?

There has been no progress within this project and no ETA for starting.

**Comment by glen-84** [comment]
It looks like this is available [here](https://github.com/slevomat/coding-standard/#slevomatcodingstandardtypehintsdeclarestricttypes-).

**Comment by jrjohnson** [comment]
This is resolved in #2365 which added [RequireStrictTypesSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/PHP/RequireStrictTypesSniff.php)

**Comment by gsherwood** [comment]
> This is resolved in #2365 which added [RequireStrictTypesSniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Sniffs/PHP/RequireStrictTypesSniff.php)

That PR was not merged - but a sniff was written and released as part of PSR12 support. So you are right, this can be closed. Thanks.
