### ISSUE TITLE
UselessOverridingMethod throws warning for methods calling parent that have different arguments 

### ISSUE THREAD

**Issue by photodude** [squizlabs/PHP_CodeSniffer#918]
Generic.CodeAnalysis.UselessOverridingMethod sniff throws a warning for methods calling the parent with different function parameters. The sniff documentation says it _"detects the use of methods that only call their parent classes's method with the same name and arguments"_ 

[Test indicating a valid override as an error](https://travis-ci.org/photodude/joomla-cms/builds/115452673#L1626)
[Code calling parent with different arguments causing the "warning"](https://github.com/photodude/joomla-cms/blob/phpcs2-testmembervar/administrator/components/com_banners/controllers/banners.php#L55)
[The parent method for the method throwing the warning](https://github.com/photodude/joomla-cms/blob/phpcs2-testmembervar/libraries/legacy/controller/legacy.php#L742)

**Comment by aik099** [comment]
That's why warning message says `Possible`, because too many false positives possible.

**Comment by gsherwood** [comment]
There is no way for the sniff to know this because it only looks at one file at a time. PHPCS allows you to check individual files or dirs, but a check like this can only be 100% correct if the entire codebase is scanned at once.

It's a sniff best used for manual code reviews so you can decide if something should be changed or not. If you don't do manual code reviews, I recommend not using this sniff.
