### ISSUE TITLE
@codingStandardsIgnoreLine only works with the single line comment sysntax

### ISSUE THREAD

**Issue by rohanvakharia** [squizlabs/PHP_CodeSniffer#931]
Hi guys,

I want to ignore only the namespace error and for that first I tried with @codingStandardsIgnoreStart and @codingStandardsIgnoreEnd. But I then I found that I can use the @codingStandardsIgnoreLine

When I write the @codingStandardsIgnoreLine using multi-line comment. It does not work.

Something like this:

```
/**
 * @codingStandardsIgnoreLine
 */

```
It only works with the single line comment 

`// @codingStandardsIgnoreLine`

The problem here is that those who are using @codingStandardsIgnoreLine, have to write the two type  function or class documentation.

Can you be able to fix this?

**Comment by gsherwood** [comment]
The `@codingStandardsIgnoreLine` function just ignores the line that the comment is on, and the following line. At that point in processing, it doesn't know where the end of the comment is so it can't go ahead and ignore the line that comes after the comment. Even if it did, it would then be impossible to ignore lines inside a docblock because `@codingStandardsIgnoreLine` would no longer ignore the following line - it would ignore the line after the entire docblock.

So the short answer is: no, this can't be changed.

If you want to use that comment style, you could instead try using `@codingStandardsIgnoreStart` and `@codingStandardsIgnoreEnd` comments and wrap those around your code.

if you actually don't want a namespace error to ever be generated on any files, you should create a custom ruleset.xml file and exclude that particular sniff or error message.

If you need help with any of those options, just let me know.
