### ISSUE TITLE
Issue with php code sniffer 2.6.0 in a bash script "while read..."

### ISSUE THREAD

**Issue by neilime** [squizlabs/PHP_CodeSniffer#953]
Hi,

I got an issue with this bash script : execute php code sniffer for several php files. I don't have this issue with php code sniffer 2.5.1.

```bash
#!/bin/bash

FILES=$(echo -e "test1.php\ntest2.php");

echo -e "\e[94m\n # Old version Check "`echo "$FILES" | wc -l`" file(s) :\n\e[0m";
while read FILE; do
    echo -e "Process file \"$FILE\"\n"
    php php-code-sniffer/2.6.0/scripts/phpcbf "$FILE"
done <<< "$FILES";
```

Output : 
```bash
Process file "test1.php"

Changing into directory test
Processing test.php [PHP => 82 tokens in 21 lines]... DONE in 7ms (0 fixable violations)
Processing STDIN [PHP => 1 tokens in 1 lines]... DONE in 0ms (0 fixable violations)
No fixable errors were found
Time: 30ms; Memory: 7.25Mb
```
Only the first file is processed by php code sniffer.

If I use this script :

```bash
#!/bin/bash

FILES=$(echo -e "test1.php\ntest2.php");
echo -e "\e[94m\n # New version Check "`echo "$FILES" | wc -l`" file(s) :\n\e[0m";
old_IFS=$IFS 
IFS=$'\n' 
for FILE in $FILES
do  
    echo -e "Process file \"$FILE\"\n"
    php php-code-sniffer/2.6.0/scripts/phpcbf "$FILE"
done;
IFS=$old_IFS
```

Output : 
```bash
 # New version Check 2 file(s) :

Process file "test1.php"

Changing into directory /.../test_repository
Processing test.php [PHP => 82 tokens in 21 lines]... DONE in 7ms (0 fixable violations)
No fixable errors were found
Time: 30ms; Memory: 7.25Mb

Process file "test2.php"

Changing into directory /.../test_repository
Processing test.php [PHP => 82 tokens in 21 lines]... DONE in 8ms (0 fixable violations)
No fixable errors were found
Time: 31ms; Memory: 7.25Mb
```
It works !

Maybe this tricks can help someone and maybe this issue can be fixed too.

**Comment by gsherwood** [comment]
The change you've made (the FOR loop) is what I would have recommended.

The change in 2.6.0 that causes this sets STDIN to non-blocking so that file content can be piped to phpcs and phpcbf directly. READ is obviously seeing this and passing the entire rest of $FILES to phpcbf, so only one run is ever processed. I don't know anywhere near enough about READ to know why it does this or if there is a way around it.

I can't change the STDIN detection to be blocking in PHPCS, so the solution you've provided will have to do. Thanks a lot for posting it and letting me know about this change.
