### ISSUE TITLE
sort rules by line and column

### ISSUE THREAD

**Issue by UziTech** [squizlabs/PHP_CodeSniffer#966]
would be nice to see results sorted by line and column

**Comment by aik099** [comment]
Maybe implementation of report that also shows code with error made in #419 would be useful to you. Not released yet.

**Comment by gsherwood** [comment]
Errors are already sorted by line and column. What are you seeing?

**Comment by UziTech** [comment]
I am using [linter-phpcs](https://github.com/atomlinter/linter-phpcs) for Atom and the errors/warning aren't listed in order.

**Comment by gsherwood** [comment]
> I am using linter-phpcs for Atom and the errors/warning aren't listed in order.

I use the same plugin and the errors appear in order for me, assuming I'm looking at the errors for a single file. Maybe you should contact the developer of the plugin if you think there is a problem with the plugin.

I'm going to close this because I can't replicate any errors in PHPCS itself. If you are able to replicate errors appearing out of order when running PHPCS directly, please comment and let me know so I can look into it.
