### ISSUE TITLE
Introduce a flag that limits the reported number of errors and warnings

### ISSUE THREAD

**Issue by ikappas** [squizlabs/PHP_CodeSniffer#971]
Thank you for this great plugin.

I have written the phpcs plugin for visual studio code found [here](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs).

I am running into slow response times while linting files that contain a lot of errors and would greatly appreciate the ability to pass in a flag to phpcs that would limit the maximum number of errors/warnings that will be reported ie. phpcs --max-errors=100 ...

This flag could either be error/warning scoped or aggregate to the total number of errors reported and would enable much faster response times from within code editors.

Thank you in advance for looking into this feature.

Ioannis Kappas

**Comment by aik099** [comment]
The PhpStorm somehow limits number of shown errors. Not sure if it tells PHP_CodeSniffer to report less errors, or just shown only first X errors from many reported by PHP_CodeSniffer.

**Comment by ikappas** [comment]
That how I do it in the plugin. Phpcs will return a result only after processing all errors. Then I limit the number of errors I report to vscode ( which by the way has a hard limit of 250/per document) and ignore the rest.

I strongly believe that there is a lot of room on improvement here.

For example lets say we have  a document that has 1200 errors and stops parsing at a specified limit of lets say 250. This means that phpcs could skip working on another 950 errors and report the first 250 errors it parses.

Now take into account running phpcs automatically on every document save. ( which I do this very often as a habit )

At the end of the day a lot of processing power and time can be saved if this issue is addressed at the phpcs level while improving IDE response times.

**Comment by gsherwood** [comment]
I like this idea, but I'd caution against making the assumption that the checking is slowing down the entire process. You might find that actually tokenizing the file is taking a significant amount of time as well, so limiting the number of errors might not help as much as you hope.

Still, anything that can help get a result faster is a good thing, and this feature will certainly help with that to some extent.

**Comment by gsherwood** [comment]
A further note that there is no way PHPCS can limit the number of errors to exactly what is asked for because I couldn't add this feature into every sniff. And even if I did, because sniffs process multiple lines at a time, you would not get a complete error report for the first part of the file.

For example, the line length sniff is going to go through every single line in the file and report errors about long lines. If it generates 10,000 errors and you limit the output to 250, the core of PHPCS is not going to be able to kill the line length sniff mid-way through its processing so it will still process the entire file. Even if it could kill the sniff, you'd end up with a report containing 250 line length errors covering who knows how many lines, instead of a mix of errors that can be fixed in in a smaller code block.

The other problem is that until you choose to fix an error, you wont be able to see any more of them. This is particularly a problem if you have things like line length errors that you want to ignore but you can't get to the rest of the report until you fix them. So your only option is to change the coding standard to turn them into warnings, or remove the check completely, or bump the error count up high enough to see some new ones.

I don't have solutions for these problems, but they seem to be blockers for getting this feature implemented. If it isn't going to be useful, and is going to end up generating a bunch more feature requests and bug reports because it doesn't work as people expect, I wont be able to put it in.

**Comment by gsherwood** [comment]
Closing as I can't see how this can be achieved.
