### ISSUE TITLE
This line shows many errors without displaying the actual error

### ISSUE THREAD

**Issue by phoenixenero** [squizlabs/PHP_CodeSniffer#991]
```php
if ( 0 > 1 ) : {
```

Similar:

```php
foreach ( $array as $item ) : {
```

Results on my php file (in Atom):

![A line that shows so many errors except the real one.](https://cloud.githubusercontent.com/assets/9031092/14981516/5245a8a0-1162-11e6-8eb4-913d3f982cc7.PNG)

**Comment by gsherwood** [comment]
Your screenshot shows that PHPCS was unable to tokenize the code because it found a possible parse error with a class definition. If there is no syntax error, maybe the syntax is not supported by PHPCS yet, or you are not using the latest version.

Either way, I'll need to see the code that is causing the problem please. I can't replicate any problems with the code snippet I can see in the screenshot or the code you've posted in the original comment.

**Comment by phoenixenero** [comment]
Ah nevermind. Just learned about [PHP statement groups](http://stackoverflow.com/q/14971123/2193396).
