### ISSUE TITLE
phpcbf could fix better

### ISSUE THREAD

**Issue by basz** [squizlabs/PHP_CodeSniffer#996]
The PSR2 rule that states : "The closing parenthesis and the opening brace of a multi-line function declaration must be on the same line".

While this is automatically fixable it does that while leaving an empty new line. Would it be possible to remove that extraneous line?

```
    public static function create(
        $addressee = null,
        $street = null,
        string $streetOrdinality = null,
        string $streetOrdinalitySuffix = null,
        string $postalCode = null,
        string $populatedPlace = null,
        Country $country = null,
        CountryRegion $region = null,
        Coordinate $geoLocation = null
    ): Address
    {
        return new static(...omited
    }
```
Will be fixed as
```
    public static function create(
        $addressee = null,
        $street = null,
        string $streetOrdinality = null,
        string $streetOrdinalitySuffix = null,
        string $postalCode = null,
        string $populatedPlace = null,
        Country $country = null,
        CountryRegion $region = null,
        Coordinate $geoLocation = null
    ): Address {
    
        return new static(...omited
    }
```
While the following would be more appropriate
```
    public static function create(
        $addressee = null,
        $street = null,
        string $streetOrdinality = null,
        string $streetOrdinalitySuffix = null,
        string $postalCode = null,
        string $populatedPlace = null,
        Country $country = null,
        CountryRegion $region = null,
        Coordinate $geoLocation = null
    ): Address {
        return new static(...omited
    }
```

**Comment by gsherwood** [comment]
It does this on purpose. The sniff only fix the specific thing they find and often leave whitespace lying around for other sniffs to clean up. If you don't want blank lines at the start of functions, you can use another sniff to enforce that and this second sniff will do the auto-fixing for you.

The reason the sniffs fix as little as possible is so that they don't conflict with each other. Because you can mix and match sniffs in your own coding standards, it is hard for a sniff to clean up after a fix in a way that will be correct for all coding standards. So it's often best to just leave the cleanup to another sniff.

Does that make sense?

**Comment by basz** [comment]
that, sniff, does makes sense ;-) merci

**Comment by gsherwood** [comment]
Great :)
